In [3]:
import tensorflow as tf
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
# fix random seed for reproducibility
np.random.seed(7)

In [4]:
def dataprocess(datalist):
    for i in datalist:
        temp = []
        for j in range(26):
            if i!=j:
                temp.append(0)
            else:
                temp.append(1)
        try:
            transfered_data = np.vstack([transfered_data, temp])
        except:
            transfered_data = temp
    return(transfered_data)

In [7]:
def caeserde_1(plaintext, key=3):
    L2I = dict(zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ", range(26)))
    I2L = dict(zip(range(26), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    ciphertext = ""
    ciphernum = []
    plainnum = []

    for c in plaintext.upper():
        if c.isalpha():
            # L2I[c]+key represents the order eg A=1 B=2
            ciphertext += I2L[(L2I[c] + key) % 26]
            ciphernum.append((L2I[c] + key) % 26)
            plainnum.append((L2I[c]) % 26)
        else:
            ciphertext += c
            ciphernum.append('-1')
    return (ciphertext, ciphernum, plainnum)
# random data
text, train, label = caeserde_1(
    'WERTYUIOPOIUGFDSASXCVBNMKJHGFREWQASXCVBNMJKUJYTFRDCVBNMKLOIUYTFCVBABCDEFTYGUHIJGFTGHJKLGYFHJRTFYGUHIJOKIHUGYFTGHJKLJHJGFJKLJHGFDCVBNMHGFDSRTRYUHIJKOIUYTREWQAZXCVBNMFGHIJKLMNOPQRSTUVWXYZ'
)

In [13]:
def caeserde_26(plaintext, key=3):
    L2I = dict(zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ", range(26)))
    I2L = dict(zip(range(26), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    ciphertext = ""
    ciphernum = []
    plainnum = []

    for c in plaintext.upper():
        if c.isalpha():
            # L2I[c]+key represents the order eg A=1 B=2
            ciphertext += I2L[(L2I[c] + key) % 26]
            ciphernum.append((L2I[c] + key) % 26)
            plainnum.append((L2I[c]) % 26)
        else:
            ciphertext += c
            ciphernum.append('-1')
    ciphernum = dataprocess(ciphernum)
    plainnum = dataprocess(plainnum)
    return (ciphertext, ciphernum, plainnum)
# random data
text, train, label = caeserde_26(
    'WERTYUIOPOIUGFDSASXCVBNMKJHGFREWQASXCVBNMJKUJYTFRDCVBNMKLOIUYTFCVBABCDEFTYGUHIJGFTGHJKLGYFHJRTFYGUHIJOKIHUGYFTGHJKLJHJGFJKLJHGFDCVBNMHGFDSRTRYUHIJKOIUYTREWQAZXCVBNMFGHIJKLMNOPQRSTUVWXYZ'
)
label

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

# TODO list
## Caeser ciper and impliment deep learning model**<br>
    Caeser encryption function prediction
## **Try to play around with caeser ciper and deep learning input and output**<br>
### input 3(d) -- output a(0)

### Model with 1 input and 26 output

In [21]:
model1 = None
model1 = Sequential()
model1.add(Dense(10, input_dim=1, activation='relu'))
model1.add(Dense(10, activation='relu'))
model1.add(Dense(1, activation='relu'))
model1.compile(loss='poisson', optimizer='adam', metrics=['accuracy'])

In [17]:
model1.fit(train, label, epochs=1000)

ValueError: Error when checking input: expected dense_4_input to have shape (1,) but got array with shape (130,)

In [18]:
train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=[]),
    tf.keras.layers.Dense(20, activation=tf.nn.relu),
    tf.keras.layers.Dense(20, activation=tf.nn.relu),
    tf.keras.layers.Dense(20, activation=tf.nn.relu),
    #tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(26, activation=tf.nn.softmax),
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    #loss = 'binary_crossentropy',
    metrics=['accuracy'])
model.summary() #20*20+20

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 1)                 0         
_________________________________________________________________
dense (Dense)                (None, 20)                40        
_________________________________________________________________
dense_1 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_2 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_3 (Dense)              (None, 26)                546       
Total params: 1,426
Trainable params: 1,426
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(train, label, epochs=1000)

ValueError: Error when checking input: expected flatten_input to have 1 dimensions, but got array with shape (2, 130)

### Model with 26 input and 26 output

In [23]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=26, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(26, activation='softmax'))

In [24]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
# random data
text, train, label = caeserde_26(
    'WERTYUIOPOIUGFDSASXCVBNMKJHGFREWQASXCVBNMJKUJYTFRDCVBNMKLOIUYTFCVBABCDEFTYGUHIJGFTGHJKLGYFHJRTFYGUHIJOKIHUGYFTGHJKLJHJGFJKLJHGFDCVBNMHGFDSRTRYUHIJKOIUYTREWQAZXCVBNMFGHIJKLMNOPQRSTUVWXYZ'
)

In [26]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 12)                324       
_________________________________________________________________
dense_11 (Dense)             (None, 20)                260       
_________________________________________________________________
dense_12 (Dense)             (None, 26)                546       
Total params: 1,130
Trainable params: 1,130
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(train, label, epochs=300)

Instructions for updating:
Use tf.cast instead.
Epoch 1/300
185/185 [==============================] - 0s 2ms/step - loss: 0.1638 - acc: 0.9615
Epoch 2/300
185/185 [==============================] - 0s 32us/step - loss: 0.1631 - acc: 0.9615
Epoch 3/300
185/185 [==============================] - 0s 32us/step - loss: 0.1624 - acc: 0.9615
Epoch 4/300
185/185 [==============================] - 0s 35us/step - loss: 0.1618 - acc: 0.9615
Epoch 5/300
185/185 [==============================] - 0s 34us/step - loss: 0.1612 - acc: 0.9615
Epoch 6/300
185/185 [==============================] - 0s 39us/step - loss: 0.1605 - acc: 0.9615
Epoch 7/300
185/185 [==============================] - 0s 37us/step - loss: 0.1598 - acc: 0.9615
Epoch 8/300
185/185 [==============================] - 0s 37us/step - loss: 0.1591 - acc: 0.9615
Epoch 9/300
185/185 [==============================] - 0s 38us/step - loss: 0.1584 - acc: 0.9615
Epoch 10/300
185/185 [==============================] - 0s 38us/step - loss: 0.1

Epoch 82/300
185/185 [==============================] - 0s 39us/step - loss: 0.0117 - acc: 0.9992
Epoch 83/300
185/185 [==============================] - 0s 39us/step - loss: 0.0111 - acc: 0.9992
Epoch 84/300
185/185 [==============================] - 0s 39us/step - loss: 0.0106 - acc: 0.9992
Epoch 85/300
185/185 [==============================] - 0s 39us/step - loss: 0.0101 - acc: 0.9992
Epoch 86/300
185/185 [==============================] - 0s 38us/step - loss: 0.0096 - acc: 0.9992
Epoch 87/300
185/185 [==============================] - 0s 37us/step - loss: 0.0092 - acc: 0.9992
Epoch 88/300
185/185 [==============================] - 0s 37us/step - loss: 0.0088 - acc: 0.9992
Epoch 89/300
185/185 [==============================] - 0s 40us/step - loss: 0.0084 - acc: 0.9992
Epoch 90/300
185/185 [==============================] - 0s 37us/step - loss: 0.0080 - acc: 0.9996
Epoch 91/300
185/185 [==============================] - 0s 38us/step - loss: 0.0077 - acc: 0.9996
Epoch 92/300
185/185

185/185 [==============================] - 0s 37us/step - loss: 2.8221e-04 - acc: 1.0000
Epoch 244/300
185/185 [==============================] - 0s 37us/step - loss: 2.7930e-04 - acc: 1.0000
Epoch 245/300
185/185 [==============================] - 0s 36us/step - loss: 2.7623e-04 - acc: 1.0000
Epoch 246/300
185/185 [==============================] - 0s 34us/step - loss: 2.7323e-04 - acc: 1.0000
Epoch 247/300
185/185 [==============================] - 0s 37us/step - loss: 2.7030e-04 - acc: 1.0000
Epoch 248/300
185/185 [==============================] - 0s 33us/step - loss: 2.6736e-04 - acc: 1.0000
Epoch 249/300
185/185 [==============================] - 0s 37us/step - loss: 2.6463e-04 - acc: 1.0000
Epoch 250/300
185/185 [==============================] - 0s 33us/step - loss: 2.6186e-04 - acc: 1.0000
Epoch 251/300
185/185 [==============================] - 0s 33us/step - loss: 2.5910e-04 - acc: 1.0000
Epoch 252/300
185/185 [==============================] - 0s 36us/step - loss: 2.5653e-0

In [13]:
predictions = model.predict(train)
rounded = [round(x[0]) for x in predictions]

In [2]:
import keras
import keras.callbacks
from keras.callbacks import TensorBoard
tensorboard = TensorBoard(log_dir = "./graphs/{}")

In [59]:
scores = model.evaluate(train, label)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

185/185 [==============================] - 0s 582us/step

acc: 100.00%


### Model with 1 input and 1 output

In [3]:
# create model
model1 = None
model1 = Sequential()
model1.add(Dense(26, input_dim=1, activation='relu'))
model1.add(Dense(20, activation='relu'))

model1.add(Dense(20, activation='relu'))
model1.add(Dense(20, activation='relu'))

model1.add(Dense(20, activation='relu'))

model1.add(Dense(1, activation='relu'))

NameError: name 'Sequential' is not defined

In [43]:
text, train, label = caeserde_26(
    'IAMSAMILIKEDST'
)

See how can we chose the loss function: https://keras.io/losses/

In [44]:
model1.compile(loss='poisson', optimizer='adam', metrics=['accuracy'])

In [57]:
# random data
text, train, label = caeserde_1(
    'WERTYUIOPOIUGFDSASXCVBNMKJHGFREWQASXCVBNMJKUJYTFRDCVBNMKLOIUYTFCVBABCDEFTYGUHIJGFTGHJKLGYFHJRTFYGUHIJOKIHUGYFTGHJKLJHJGFJKLJHGFDCVBNMHGFDSRTRYUHIJKOIUYTREWQAZXCVBNMFGHIJKLMNOPQRSTUVWXYZWERTYUIOPOIUGFDSASXCVBNMKJHGFREWQASXCVBNMJKUJYTFRDCVBNMKLOIUYTFCVBABCDEFTYGUHIJGFTGHJKLGYFHJRTFYGUHIJOKIHUGYFTGHJKLJHJGFJKL'
)
model1.fit(train, label, epochs=500)

Epoch 1/500
308/308 [==============================] - 0s 52us/step - loss: 184.6778 - acc: 0.0227
Epoch 2/500
308/308 [==============================] - 0s 46us/step - loss: 184.6778 - acc: 0.0227
Epoch 3/500
308/308 [==============================] - 0s 52us/step - loss: 184.6778 - acc: 0.0227
Epoch 4/500
308/308 [==============================] - 0s 54us/step - loss: 184.6778 - acc: 0.0227
Epoch 5/500
308/308 [==============================] - 0s 66us/step - loss: 184.6778 - acc: 0.0227
Epoch 6/500
308/308 [==============================] - 0s 59us/step - loss: 184.6778 - acc: 0.0227
Epoch 7/500
308/308 [==============================] - 0s 43us/step - loss: 184.6778 - acc: 0.0227
Epoch 8/500
308/308 [==============================] - 0s 48us/step - loss: 184.6778 - acc: 0.0227
Epoch 9/500
308/308 [==============================] - 0s 55us/step - loss: 184.6778 - acc: 0.0227
Epoch 10/500
308/308 [==============================] - 0s 51us/step - loss: 184.6778 - acc: 0.0227
Epoch 11/

308/308 [==============================] - 0s 47us/step - loss: 184.6778 - acc: 0.0227
Epoch 84/500
308/308 [==============================] - 0s 46us/step - loss: 184.6778 - acc: 0.0227
Epoch 85/500
308/308 [==============================] - 0s 42us/step - loss: 184.6778 - acc: 0.0227
Epoch 86/500
308/308 [==============================] - 0s 40us/step - loss: 184.6778 - acc: 0.0227
Epoch 87/500
308/308 [==============================] - 0s 43us/step - loss: 184.6778 - acc: 0.0227
Epoch 88/500
308/308 [==============================] - 0s 43us/step - loss: 184.6778 - acc: 0.0227
Epoch 89/500
308/308 [==============================] - 0s 45us/step - loss: 184.6778 - acc: 0.0227
Epoch 90/500
308/308 [==============================] - 0s 43us/step - loss: 184.6778 - acc: 0.0227
Epoch 91/500
308/308 [==============================] - 0s 42us/step - loss: 184.6778 - acc: 0.0227
Epoch 92/500
308/308 [==============================] - 0s 42us/step - loss: 184.6778 - acc: 0.0227
Epoch 93/500


308/308 [==============================] - 0s 44us/step - loss: 184.6778 - acc: 0.0227
Epoch 246/500
308/308 [==============================] - 0s 44us/step - loss: 184.6778 - acc: 0.0227
Epoch 247/500
308/308 [==============================] - 0s 47us/step - loss: 184.6778 - acc: 0.0227
Epoch 248/500
308/308 [==============================] - 0s 49us/step - loss: 184.6778 - acc: 0.0227
Epoch 249/500
308/308 [==============================] - 0s 49us/step - loss: 184.6778 - acc: 0.0227
Epoch 250/500
308/308 [==============================] - 0s 48us/step - loss: 184.6778 - acc: 0.0227
Epoch 251/500
308/308 [==============================] - 0s 47us/step - loss: 184.6778 - acc: 0.0227
Epoch 252/500
308/308 [==============================] - 0s 47us/step - loss: 184.6778 - acc: 0.0227
Epoch 253/500
308/308 [==============================] - 0s 46us/step - loss: 184.6778 - acc: 0.0227
Epoch 254/500
308/308 [==============================] - 0s 45us/step - loss: 184.6778 - acc: 0.0227
Epoc

308/308 [==============================] - 0s 47us/step - loss: 184.6778 - acc: 0.0227
Epoch 408/500
308/308 [==============================] - 0s 46us/step - loss: 184.6778 - acc: 0.0227
Epoch 409/500
308/308 [==============================] - 0s 47us/step - loss: 184.6778 - acc: 0.0227
Epoch 410/500
308/308 [==============================] - 0s 44us/step - loss: 184.6778 - acc: 0.0227
Epoch 411/500
308/308 [==============================] - 0s 42us/step - loss: 184.6778 - acc: 0.0227
Epoch 412/500
308/308 [==============================] - 0s 45us/step - loss: 184.6778 - acc: 0.0227
Epoch 413/500
308/308 [==============================] - 0s 42us/step - loss: 184.6778 - acc: 0.0227
Epoch 414/500
308/308 [==============================] - 0s 43us/step - loss: 184.6778 - acc: 0.0227
Epoch 415/500
308/308 [==============================] - 0s 44us/step - loss: 184.6778 - acc: 0.0227
Epoch 416/500
308/308 [==============================] - 0s 41us/step - loss: 184.6778 - acc: 0.0227
Epoc

In [39]:
model1.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_28 (Dense)             (None, 26)                52        
_________________________________________________________________
dense_29 (Dense)             (None, 20)                540       
_________________________________________________________________
dense_30 (Dense)             (None, 20)                420       
_________________________________________________________________
dense_31 (Dense)             (None, 20)                420       
_________________________________________________________________
dense_32 (Dense)             (None, 20)                420       
_________________________________________________________________
dense_33 (Dense)             (None, 1)                 21        
Total params: 1,873
Trainable params: 1,873
Non-trainable params: 0
_________________________________________________________________


### input 3(d) -- output (1,0,0,...,0)

### input (0,0,0,1,0,...,0) -- output a(0)

### input (0,0,0,1,0,...,0) -- output (1,0,0,...,0)

### input (0,0,0,1,0,...,0) -- output (1,0,0,...,0)

## **Analyse this results**<br>

   For example, which model minimises the number of echos 
   Which model cannot reach the 100% accuracy? Why?
   

## **Using unseen data 26-100**<br>

    The model has seen 0-26)<br>
    Try to find the weight in this model<br>
    Try to visualize it by using tensorboard<br>

## **Try to add more training data, see if things change**<br>
    If it is better, try to explain why<br>
    If it is not, maybe 23 is enough?<br>
* My prior: Maybe more data can make the training procedure faster? I don't know given the same input how doesthe neural network learn? Stop updating or **keep updating**?<br>

## **Try to hide some data**
* For human, it is reasonable if we hide z, we are able to judge the one we cannot see (high probability)
* I tried it makes no sense so far. 98%?<br>

## Add new data to make the neural network learn the shift, but how to learn the piecewise function

## **Try to given pairs of data, and change the structure of neural output and input**
* How many we combination we have? **676** (no order). More deeperly, combining with more words (we know the number of combination is too large, we just want to test, if neural network could learn something unseen?
* Need a smart way to do this (consider to restruct the input and output as well as the order)<br>


<table>
<tr><th>Example 1 </th><th>Example 2</th></tr>
<tr><td>

Set|Input| Output|Seen
---|---|---|---|
Training| AB | DE |Yes
Training| CD | FG |Yes
Testing | BC | EF |No

</td><td>


Set|Input| Output|Seen
---|---|---|---|
Training| AB | DE |Yes
Testing | BA | ED |No

</td></tr> </table>

* Idea: <br>

## **Watching videos and papers for logic programming**

    To figure out logic programming in deep learning
    Video<br>
    [Deep learning course: Introduction to Deep Learning](https://www.youtube.com/watch?v=JN6H4rQvwgY)<br>
    [Richard Evans: Inductive logic programming and deep learning I](https://www.youtube.com/watch?v=yD02DlZnHJw)<br>
    [Learning Explanatory Rules from Noisy Data - Richard Evans, DeepMind](https://www.youtube.com/watch?v=_wuFBF_Cgm0&t=24s)<br>
    Paper<br>
    [LOGIC MINING USING NEURAL NETWORKS](https://arxiv.org/pdf/0804.4071.pdf)<br>
    [First-order Logic Learning in Artificial Neural Networks](https://core.ac.uk/download/pdf/17294404.pdf)<br>
    Python logic programming<br>
    [PYKE](http://pyke.sourceforge.net/index.html)

- [ ] **Try to use ILD to guide our neural system**
    How? Set rules, recurrent?

- [ ] **Try to find new encryption function to learn more complex stuff**
    key=[1,2,3,4]? 
    Consider the input and output

## letters position matrix

In [2]:
def caeserde_1(plaintext, key=3):
    L2I = dict(zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ", range(26)))
    I2L = dict(zip(range(26), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    ciphertext = ""
    ciphernum = []
    plainnum = []

    for c in plaintext.upper():
        if c.isalpha():
            # L2I[c]+key represents the order eg A=1 B=2
            ciphertext += I2L[(L2I[c] + key) % 26]
            ciphernum.append((L2I[c] + key) % 26)
            plainnum.append((L2I[c]) % 26)
        else:
            ciphertext += c
            ciphernum.append('-1')
    return (ciphertext, ciphernum, plainnum)
def letter_position_matrix(text,key=3):
    length = len(text)
    matrix = [[0 for y in range(26)] for x in range(length)]
    for idx, val in enumerate(text):
        matrix[idx][val] = 1
    matrix = np.array(matrix)
    return matrix




In [31]:
ciphertext, ciphernum, plainnum = caeserde_1("Hello")


a = letter_position_matrix(plainnum)
b = letter_position_matrix(ciphernum)

label_smaller = np.array(plainnum)
# flatten label and training set
label_equalsize = a.flatten()
train = b.flatten()


130

In [55]:
import random
import string
random.seed(1)

In [186]:
def data_genelization(k=2,loops = 1000):
    temp = ''.join(random.choices(string.ascii_uppercase, k=2))
    ciphertext, ciphernum, plainnum = caeserde_1(temp)

    a = letter_position_matrix(plainnum)
    b = letter_position_matrix(ciphernum)

    label_smaller = np.array(plainnum)
    # flatten label and training set
    label_equalsize = a.flatten()
    train = b.flatten()
    for i in range(loops):
        temp = ''.join(random.choices(string.ascii_uppercase, k=2))
        ciphertext, ciphernum, plainnum = caeserde_1(temp)
        a = letter_position_matrix(plainnum)
        b = letter_position_matrix(ciphernum)
        label_smaller = np.vstack([label_smaller,np.array(plainnum)])
        # flatten label and training set
        label_equalsize = np.vstack([label_equalsize,a.flatten()])
        train = np.vstack([train,b.flatten()])
    return(train,label_equalsize,label_smaller)
        


In [188]:
train,label_equalsize,label_smaller = data_genelization(loops=10000)
# loops = 5000 accuracy will stay in 98% maybe they not see all the data set?


In [189]:
# create model
model = Sequential()
model.add(Dense(20, input_dim=52, activation='relu'))
model.add(Dense(20, activation='relu'))

model.add(Dense(52, activation='sigmoid'))#01 so sigmoid is better?>

In [190]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#logcosh reduce the accuracy 52-2

In [197]:
model.fit(train, label_equalsize, epochs=1000, batch_size= 1000)
#repeat a lot of time to get 100% accuracy

Epoch 1/1000
10001/10001 [==============================] - 0s 5us/step - loss: 0.0074 - acc: 0.9988
Epoch 2/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0073 - acc: 0.9988
Epoch 3/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0072 - acc: 0.9988
Epoch 4/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0071 - acc: 0.9988
Epoch 5/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0070 - acc: 0.9988
Epoch 6/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0070 - acc: 0.9988
Epoch 7/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0069 - acc: 0.9988
Epoch 8/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0069 - acc: 0.9989
Epoch 9/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0069 - acc: 0.9989
Epoch 10/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0069 - a

10001/10001 [==============================] - 0s 4us/step - loss: 0.0031 - acc: 0.9998
Epoch 161/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0031 - acc: 0.9998
Epoch 162/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0030 - acc: 0.9998
Epoch 163/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0030 - acc: 0.9998
Epoch 164/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0030 - acc: 0.9998
Epoch 165/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0030 - acc: 0.9998
Epoch 166/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0030 - acc: 0.9998
Epoch 167/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0029 - acc: 0.9998
Epoch 168/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0029 - acc: 0.9998
Epoch 169/1000
10001/10001 [==============================] - 0s 4us/step - loss: 0.0029

10001/10001 [==============================] - 0s 5us/step - loss: 9.9712e-04 - acc: 1.0000
Epoch 319/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.8912e-04 - acc: 1.0000
Epoch 320/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.8341e-04 - acc: 1.0000
Epoch 321/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.8813e-04 - acc: 1.0000
Epoch 322/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.9452e-04 - acc: 1.0000
Epoch 323/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.7393e-04 - acc: 1.0000
Epoch 324/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.5875e-04 - acc: 1.0000
Epoch 325/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.5340e-04 - acc: 1.0000
Epoch 326/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.4969e-04 - acc: 1.0000
Epoch 327/1000
10001/10001 [========================

10001/10001 [==============================] - 0s 4us/step - loss: 3.1753e-04 - acc: 1.0000
Epoch 471/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.1422e-04 - acc: 1.0000
Epoch 472/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.1210e-04 - acc: 1.0000
Epoch 473/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.1065e-04 - acc: 1.0000
Epoch 474/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.0789e-04 - acc: 1.0000
Epoch 475/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.0622e-04 - acc: 1.0000
Epoch 476/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.0470e-04 - acc: 1.0000
Epoch 477/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.0247e-04 - acc: 1.0000
Epoch 478/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.0307e-04 - acc: 1.0000
Epoch 479/1000
10001/10001 [========================

10001/10001 [==============================] - 0s 4us/step - loss: 1.0692e-04 - acc: 1.0000
Epoch 623/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.0516e-04 - acc: 1.0000
Epoch 624/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.0369e-04 - acc: 1.0000
Epoch 625/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.0267e-04 - acc: 1.0000
Epoch 626/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.0154e-04 - acc: 1.0000
Epoch 627/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.0051e-04 - acc: 1.0000
Epoch 628/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.9836e-05 - acc: 1.0000
Epoch 629/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.9526e-05 - acc: 1.0000
Epoch 630/1000
10001/10001 [==============================] - 0s 4us/step - loss: 9.9704e-05 - acc: 1.0000
Epoch 631/1000
10001/10001 [========================

10001/10001 [==============================] - 0s 4us/step - loss: 3.7436e-05 - acc: 1.0000
Epoch 775/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.6973e-05 - acc: 1.0000
Epoch 776/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.6503e-05 - acc: 1.0000
Epoch 777/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.6127e-05 - acc: 1.0000
Epoch 778/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.5804e-05 - acc: 1.0000
Epoch 779/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.5560e-05 - acc: 1.0000
Epoch 780/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.5342e-05 - acc: 1.0000
Epoch 781/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.5084e-05 - acc: 1.0000
Epoch 782/1000
10001/10001 [==============================] - 0s 4us/step - loss: 3.4961e-05 - acc: 1.0000
Epoch 783/1000
10001/10001 [========================

10001/10001 [==============================] - 0s 4us/step - loss: 1.3425e-05 - acc: 1.0000
Epoch 927/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.3318e-05 - acc: 1.0000
Epoch 928/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.3245e-05 - acc: 1.0000
Epoch 929/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.3167e-05 - acc: 1.0000
Epoch 930/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.3076e-05 - acc: 1.0000
Epoch 931/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.2980e-05 - acc: 1.0000
Epoch 932/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.2903e-05 - acc: 1.0000
Epoch 933/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.2936e-05 - acc: 1.0000
Epoch 934/1000
10001/10001 [==============================] - 0s 4us/step - loss: 1.2977e-05 - acc: 1.0000
Epoch 935/1000
10001/10001 [========================

In [198]:
ciphertext, ciphernum, plainnum = caeserde_1("He")

a = letter_position_matrix(plainnum)
b = letter_position_matrix(ciphernum)

label_smaller1 = np.array(plainnum)
# flatten label and training set
label_equalsize1 = a.flatten()
train1 = b.flatten()
train1 = np.vstack([train1,b.flatten()])


In [200]:
train1[0].reshape(2,26)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]])

In [201]:
model.predict(train)[0].reshape(2,26)

array([[2.6822090e-07, 0.0000000e+00, 0.0000000e+00, 1.1026859e-06,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.5765429e-05, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        3.1888485e-06, 1.4901161e-07, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 9.0897083e-06, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 9.9999219e-01,
        0.0000000e+00, 0.0000000e+00],
       [2.9802322e-07, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0430813e-06, 0.0000000e+00, 4.7683716e-07, 9.9999994e-01,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.4901161e-07, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 5.9604645e-08, 0.0000000e+00, 0.0000000e+00,
        2.9802322e-08, 0.0000000e+00]], dtype=float32)

In [203]:
scores = model.evaluate(train1, np.vstack([label_equalsize1,b.flatten()]))

2/2 [==============================] - 0s 207ms/step


In [204]:
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))


acc: 96.15%


In [53]:
train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [44]:
train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
label_equalsize

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
label_equalsize.shape[0]

1001

In [90]:
train.shape[1]

52

In [104]:
label_smaller

array([[ 2,  5],
       [24,  9],
       [15,  8],
       ...,
       [23, 15],
       [17, 13],
       [ 0,  7]])

In [19]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM#, CuDNNLSTM

model = Sequential()

# IF you are running with a GPU, try out the CuDNNLSTM layer type instead (don't pass an activation, tanh is required)
model.add(LSTM(128, input_dim=26, activation='relu', return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(26, activation='softmax'))

opt = tf.keras.optimizers.Adam(lr=0.001, decay=1e-6)

# Compile model
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy'],
)


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/Users/xihajun/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  import sys
/Users/xihajun/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(128, activation="relu", return_sequences=True, input_shape=(None, 26))`
  import sys


ValueError: Could not interpret optimizer identifier: <tensorflow.python.keras.optimizers.Adam object at 0xb2d2b2978>

In [15]:
train.shape[1:]

(26,)

In [17]:
train

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])