In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
# fix random seed for reproducibility
np.random.seed(7)

Using TensorFlow backend.


In [2]:
# first we need to creat a training dataset
def caeserde(plaintext, key=3):
    L2I = dict(zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ", range(26)))
    I2L = dict(zip(range(26), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    ciphertext = ""
    ciphernum = []
    plainnum = []
    
    for c in plaintext.upper():
        if c.isalpha():
            # L2I[c]+key represents the order eg A=1 B=2
            ciphertext += I2L[(L2I[c] + key) % 26]
            ciphernum.append((L2I[c] + key) % 26)
            plainnum.append((L2I[c]) % 26)
        else:
            ciphertext += c
            ciphernum.append('-1')
    return (ciphertext, ciphernum, plainnum)

In [3]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=26, activation='relu'))
model.add(Dense(20, activation='relu'))

model.add(Dense(26, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [5]:
text, train, label = caeserde(
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
)
for i in label:
    temp = []
    for j in range(26):
        if i!=j:
            temp.append(0)
        else:
            temp.append(1)
    try:
        A = np.vstack([A, temp])
    except:
        A = temp
for i in train:
    temp = []
    for j in range(26):
        if i!=j:
            temp.append(0)
        else:
            temp.append(1)
    try:
        X = np.vstack([X, temp])
    except:
        X = temp`
model.fit(X, A, epochs=500)

Instructions for updating:
Use tf.cast instead.
Epoch 1/500
25/25 [==============================] - 0s 8ms/step - loss: 0.1635 - acc: 0.9615
Epoch 2/500
25/25 [==============================] - 0s 49us/step - loss: 0.1634 - acc: 0.9615
Epoch 3/500
25/25 [==============================] - 0s 43us/step - loss: 0.1633 - acc: 0.9615
Epoch 4/500
25/25 [==============================] - 0s 46us/step - loss: 0.1632 - acc: 0.9615
Epoch 5/500
25/25 [==============================] - 0s 42us/step - loss: 0.1631 - acc: 0.9615
Epoch 6/500
25/25 [==============================] - 0s 49us/step - loss: 0.1629 - acc: 0.9615
Epoch 7/500
25/25 [==============================] - 0s 43us/step - loss: 0.1628 - acc: 0.9615
Epoch 8/500
25/25 [==============================] - 0s 41us/step - loss: 0.1627 - acc: 0.9615
Epoch 9/500
25/25 [==============================] - 0s 44us/step - loss: 0.1626 - acc: 0.9615
Epoch 10/500
25/25 [==============================] - 0s 44us/step - loss: 0.1625 - acc: 0.9615
Ep

Epoch 84/500
25/25 [==============================] - 0s 47us/step - loss: 0.1504 - acc: 0.9615
Epoch 85/500
25/25 [==============================] - 0s 43us/step - loss: 0.1501 - acc: 0.9615
Epoch 86/500
25/25 [==============================] - 0s 51us/step - loss: 0.1498 - acc: 0.9615
Epoch 87/500
25/25 [==============================] - 0s 44us/step - loss: 0.1495 - acc: 0.9615
Epoch 88/500
25/25 [==============================] - 0s 44us/step - loss: 0.1492 - acc: 0.9615
Epoch 89/500
25/25 [==============================] - 0s 43us/step - loss: 0.1490 - acc: 0.9615
Epoch 90/500
25/25 [==============================] - 0s 48us/step - loss: 0.1487 - acc: 0.9615
Epoch 91/500
25/25 [==============================] - 0s 50us/step - loss: 0.1484 - acc: 0.9615
Epoch 92/500
25/25 [==============================] - 0s 47us/step - loss: 0.1481 - acc: 0.9615
Epoch 93/500
25/25 [==============================] - 0s 52us/step - loss: 0.1478 - acc: 0.9615
Epoch 94/500
25/25 [====================

Epoch 169/500
25/25 [==============================] - 0s 65us/step - loss: 0.1098 - acc: 0.9615
Epoch 170/500
25/25 [==============================] - 0s 48us/step - loss: 0.1091 - acc: 0.9615
Epoch 171/500
25/25 [==============================] - 0s 57us/step - loss: 0.1084 - acc: 0.9615
Epoch 172/500
25/25 [==============================] - 0s 46us/step - loss: 0.1077 - acc: 0.9615
Epoch 173/500
25/25 [==============================] - 0s 53us/step - loss: 0.1070 - acc: 0.9615
Epoch 174/500
25/25 [==============================] - 0s 54us/step - loss: 0.1063 - acc: 0.9615
Epoch 175/500
25/25 [==============================] - 0s 61us/step - loss: 0.1056 - acc: 0.9615
Epoch 176/500
25/25 [==============================] - 0s 53us/step - loss: 0.1049 - acc: 0.9615
Epoch 177/500
25/25 [==============================] - 0s 59us/step - loss: 0.1041 - acc: 0.9615
Epoch 178/500
25/25 [==============================] - 0s 59us/step - loss: 0.1034 - acc: 0.9615
Epoch 179/500
25/25 [=========

Epoch 254/500
25/25 [==============================] - 0s 49us/step - loss: 0.0470 - acc: 0.9846
Epoch 255/500
25/25 [==============================] - 0s 51us/step - loss: 0.0464 - acc: 0.9846
Epoch 256/500
25/25 [==============================] - 0s 53us/step - loss: 0.0457 - acc: 0.9862
Epoch 257/500
25/25 [==============================] - 0s 52us/step - loss: 0.0451 - acc: 0.9862
Epoch 258/500
25/25 [==============================] - 0s 50us/step - loss: 0.0444 - acc: 0.9862
Epoch 259/500
25/25 [==============================] - 0s 66us/step - loss: 0.0438 - acc: 0.9862
Epoch 260/500
25/25 [==============================] - 0s 43us/step - loss: 0.0432 - acc: 0.9862
Epoch 261/500
25/25 [==============================] - 0s 57us/step - loss: 0.0426 - acc: 0.9877
Epoch 262/500
25/25 [==============================] - 0s 52us/step - loss: 0.0419 - acc: 0.9877
Epoch 263/500
25/25 [==============================] - 0s 52us/step - loss: 0.0413 - acc: 0.9877
Epoch 264/500
25/25 [=========

Epoch 339/500
25/25 [==============================] - 0s 64us/step - loss: 0.0118 - acc: 1.0000
Epoch 340/500
25/25 [==============================] - 0s 53us/step - loss: 0.0116 - acc: 1.0000
Epoch 341/500
25/25 [==============================] - 0s 51us/step - loss: 0.0114 - acc: 1.0000
Epoch 342/500
25/25 [==============================] - 0s 48us/step - loss: 0.0112 - acc: 1.0000
Epoch 343/500
25/25 [==============================] - 0s 47us/step - loss: 0.0111 - acc: 1.0000
Epoch 344/500
25/25 [==============================] - 0s 49us/step - loss: 0.0109 - acc: 1.0000
Epoch 345/500
25/25 [==============================] - 0s 51us/step - loss: 0.0107 - acc: 1.0000
Epoch 346/500
25/25 [==============================] - 0s 51us/step - loss: 0.0105 - acc: 1.0000
Epoch 347/500
25/25 [==============================] - 0s 45us/step - loss: 0.0104 - acc: 1.0000
Epoch 348/500
25/25 [==============================] - 0s 57us/step - loss: 0.0102 - acc: 1.0000
Epoch 349/500
25/25 [=========

Epoch 424/500
25/25 [==============================] - 0s 62us/step - loss: 0.0039 - acc: 1.0000
Epoch 425/500
25/25 [==============================] - 0s 58us/step - loss: 0.0039 - acc: 1.0000
Epoch 426/500
25/25 [==============================] - 0s 58us/step - loss: 0.0039 - acc: 1.0000
Epoch 427/500
25/25 [==============================] - 0s 55us/step - loss: 0.0038 - acc: 1.0000
Epoch 428/500
25/25 [==============================] - 0s 52us/step - loss: 0.0038 - acc: 1.0000
Epoch 429/500
25/25 [==============================] - 0s 99us/step - loss: 0.0037 - acc: 1.0000
Epoch 430/500
25/25 [==============================] - 0s 59us/step - loss: 0.0037 - acc: 1.0000
Epoch 431/500
25/25 [==============================] - 0s 74us/step - loss: 0.0037 - acc: 1.0000
Epoch 432/500
25/25 [==============================] - 0s 65us/step - loss: 0.0036 - acc: 1.0000
Epoch 433/500
25/25 [==============================] - 0s 68us/step - loss: 0.0036 - acc: 1.0000
Epoch 434/500
25/25 [=========

In [54]:
#model.fit(train, A, epochs=1000, batch_size=10)
text, train, label = caeserde(
    'Z'
)
testlabel

[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [59]:
# evaluate the model

text, train, label = caeserde(
    'ZZZZZ'
)
test = None
testlabel = None

for i in label:
    temp = []
    for j in range(26):
        if i!=j:
            temp.append(0)
        else:
            temp.append(1)
    try:
        test = np.vstack([test, temp])
    except:
        test = temp
for i in train:
    temp = []
    for j in range(26):
        if i!=j:
            temp.append(0)
        else:
            temp.append(1)
    try:
        testlabel = np.vstack([testlabel, temp])
    except:
        testlabel = temp

scores = model.evaluate(testlabel, test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

5/5 [==============================] - 0s 113us/step

acc: 96.15%


In [77]:
predictions = model.predict(test)
rounded = [round(x[0]) for x in predictions]

NameError: name 'which' is not defined

In [79]:
np.argmax(predictions, axis=1)

array([22, 22, 22, 22, 22])

In [80]:
test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1]])

In [81]:
testlabel

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]])

In [83]:
scores

[0.35687583684921265, 0.9615384340286255]