In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from myfun import caeserde
from myfun import data_genelization
from myfun import data_test
key = 3
size = 26

Using TensorFlow backend.


In [3]:
help(data_genelization)

Help on function data_genelization in module myfun:

data_genelization(sample_size=2, loops=1000, size=26, key=3, x_as_vector=False, y_as_vector=False)
    data_genelization(sample_size = 2,loops = 1000, size = 26, key = 3, x_as_vector = False, y_as_vector = False):
    return x_train, label with equual size, labels with 1 dimension



In [4]:
# example
x_train, y_train, y_train_small = data_genelization()

In [5]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model
model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
model.fit(x_train,y_train,epochs = 200)

Instructions for updating:
Use tf.cast instead.
Epoch 1/200
1000/1000 [==============================] - 0s 229us/step - loss: 0.6740 - acc: 0.6694
Epoch 2/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.5854 - acc: 0.8948
Epoch 3/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.3808 - acc: 0.9544
Epoch 4/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.2030 - acc: 0.9615
Epoch 5/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1679 - acc: 0.9615
Epoch 6/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1643 - acc: 0.9615
Epoch 7/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1624 - acc: 0.9615
Epoch 8/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1610 - acc: 0.9615
Epoch 9/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1598 - acc: 0.9615
Epoch 10/200
1000/1000 [==============================] - 0s

1000/1000 [==============================] - 0s 31us/step - loss: 0.0099 - acc: 0.9980
Epoch 81/200
1000/1000 [==============================] - 0s 31us/step - loss: 0.0095 - acc: 0.9981
Epoch 82/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.0091 - acc: 0.9982
Epoch 83/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0087 - acc: 0.9982
Epoch 84/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0084 - acc: 0.9985
Epoch 85/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0080 - acc: 0.9984
Epoch 86/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0077 - acc: 0.9987
Epoch 87/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0074 - acc: 0.9986
Epoch 88/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0071 - acc: 0.9987
Epoch 89/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0068 - acc: 0.9988
Epoch 90/200


1000/1000 [==============================] - 0s 27us/step - loss: 5.8939e-04 - acc: 1.0000
Epoch 161/200
1000/1000 [==============================] - 0s 29us/step - loss: 5.7181e-04 - acc: 1.0000
Epoch 162/200
1000/1000 [==============================] - 0s 29us/step - loss: 5.5753e-04 - acc: 1.0000
Epoch 163/200
1000/1000 [==============================] - 0s 28us/step - loss: 5.4137e-04 - acc: 1.0000
Epoch 164/200
1000/1000 [==============================] - 0s 27us/step - loss: 5.2831e-04 - acc: 1.0000
Epoch 165/200
1000/1000 [==============================] - 0s 26us/step - loss: 5.1275e-04 - acc: 1.0000
Epoch 166/200
1000/1000 [==============================] - 0s 27us/step - loss: 4.9959e-04 - acc: 1.0000
Epoch 167/200
1000/1000 [==============================] - 0s 26us/step - loss: 4.8655e-04 - acc: 1.0000
Epoch 168/200
1000/1000 [==============================] - 0s 26us/step - loss: 4.7297e-04 - acc: 1.0000
Epoch 169/200
1000/1000 [==============================] - 0s 27us/st

In [6]:
predictions = model.predict(x_train)

In [7]:
def num2str(index1, index2, size = 26):
    I2L = dict(zip(range(size), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    return ([I2L[index1], I2L[index2]])


def predict_results_only_2(model, x_train, y_train):
    predictions = model.predict(x_train)
    # index1, index2, label1, label2 represent two predictions and two labels respectively
    index1 = np.argmax(predictions[:, 0:26], axis=1)
    index2 = np.argmax(predictions[:, 26:52], axis=1)
    label1 = np.argmax(y_train[:, 0:26], axis=1)
    label2 = np.argmax(y_train[:, 26:52], axis=1)

    # Change number to string and do an output
    prediction_list = list(map(num2str, index1, index2))
    label_list = list(map(num2str, label1, label2))

    return (prediction_list, label_list)


# 理论上只要把矩阵转成字符就好了

In [8]:
def find_diff(list1, list2):
    if "".join(list1) != "".join(list2):
        print("".join(list1), "".join(list2))
        return("".join(list1), "".join(list2))
    else:
        return(True)

In [9]:
x_test, y_test, y_test_small = data_genelization()
scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)

for i in range(len(prediction_list)):
    print("".join(prediction_list[i]), "".join(label_list[i]))

1000/1000 [==============================] - 0s 37us/step

acc: 99.70%
QL QL
JO JO
GS GS
UL UL
OE OE
YT YT
WR WR
MJ MJ
RW RW
FT FT
RO RO
IR IR
LP LP
QP QP
OB OB
JC JC
PF PF
CZ CZ
YN YN
II II
CR CR
JZ JZ
TF TF
NI NI
JA JA
OC OC
BA BA
TH TH
MV MV
NC NK
CA CA
LE LE
KI KI
VI VI
VG VG
CA CA
ZV ZV
OW OM
TW TW
BE BE
MM MM
IH IH
RN RN
SD SD
NZ NZ
MW MW
RT RT
MW MW
DR DR
XD XD
WG WG
PM PM
YF YF
LO LO
KG KG
NV NV
AX AX
NF NF
SN SN
IH IH
YO YO
WW WW
QT QT
SP SP
EV EV
BV BV
TL TL
TB ZB
EG EG
PG PG
KX KX
ON ON
TZ TZ
BB BB
HR HR
KX KX
WZ WZ
TW TW
RU RU
ZV ZV
OZ OZ
RN RN
ZW ZW
DU DU
GA GA
XE XE
XD XD
CJ CJ
IY IY
FF FF
VS VS
DX DX
AI AI
EM EM
WB WB
IG IG
FY FY
RO RO
UN UN
FK FK
WQ WQ
VK VK
GD GD
PP PP
VT VT
PX PX
XJ XJ
FW FW
KV KV
UI UI
PD PD
NB NB
SF SF
UX UX
JE JE
XL XL
KA KA
BH BH
HG HG
ST ST
ZX ZX
JK JK
GL GL
JF JF
PI PI
QP QP
QU QU
OD OD
VC VC
AM AM
TU TU
RL RL
QI QI
ML ML
ST ST
VJ VJ
BV BV
IO IO
DI DI
UQ UQ
HK HK
MD MD
MT MT
EH EH
ZP ZP
JV JV
WL WL
BB BB
LZ LZ
DA DA
HM HM
LL LL
VN VN
FY FY
SB SB

In [10]:
diff = list(map(find_diff, prediction_list, label_list))
diff[i]

NC NK
OW OM
TB ZB
BG UF
PE PK
NC NK
TB ZB
OI MN
OI MN
TB ZB
EG EE
EG EE
OW OM
BG UF
JN PN
UW LM
PE PK
RK GK
RK GK
RK GK
TB ZB


True

In [17]:
temp = ["NC"]
for i in range(1000):
    temp.append("NC")
x_test, y_test, y_test_small = data_test(temp)
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)
diff = list(map(find_diff, prediction_list, label_list))


In [18]:
diff

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,

The accuracy didn't go to 1 but remained at 50% level.(when 26)
Try more training sets.

In [19]:
x_train, y_train, y_train_small = data_genelization(sample_size=3)

In [20]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model

model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
model.fit(x_train,y_train,epochs = 300)

Epoch 1/300
1000/1000 [==============================] - 0s 274us/step - loss: 0.6673 - acc: 0.6910
Epoch 2/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.5505 - acc: 0.9302
Epoch 3/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.3214 - acc: 0.9615
Epoch 4/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1850 - acc: 0.9615
Epoch 5/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.1678 - acc: 0.9615
Epoch 6/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.1648 - acc: 0.9615
Epoch 7/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1632 - acc: 0.9615
Epoch 8/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1619 - acc: 0.9615
Epoch 9/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1608 - acc: 0.9615
Epoch 10/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1598 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 27us/step - loss: 0.0354 - acc: 0.9890
Epoch 84/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0346 - acc: 0.9893
Epoch 85/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0338 - acc: 0.9896
Epoch 86/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0332 - acc: 0.9899
Epoch 87/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0325 - acc: 0.9904
Epoch 88/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0318 - acc: 0.9903
Epoch 89/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0312 - acc: 0.9908
Epoch 90/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0305 - acc: 0.9908
Epoch 91/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0300 - acc: 0.9912
Epoch 92/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0293 - acc: 0.9914
Epoch 93/300


1000/1000 [==============================] - 0s 27us/step - loss: 0.0083 - acc: 0.9984
Epoch 165/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0082 - acc: 0.9984
Epoch 166/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0080 - acc: 0.9984
Epoch 167/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0079 - acc: 0.9984
Epoch 168/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0077 - acc: 0.9986
Epoch 169/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0076 - acc: 0.9986
Epoch 170/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0075 - acc: 0.9986
Epoch 171/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0073 - acc: 0.9987
Epoch 172/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0072 - acc: 0.9987
Epoch 173/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0071 - acc: 0.9988
Epoc

1000/1000 [==============================] - 0s 27us/step - loss: 0.0019 - acc: 1.0000
Epoch 246/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0019 - acc: 1.0000
Epoch 247/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0018 - acc: 1.0000
Epoch 248/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0018 - acc: 1.0000
Epoch 249/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0017 - acc: 1.0000
Epoch 250/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0017 - acc: 1.0000
Epoch 251/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0017 - acc: 1.0000
Epoch 252/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0017 - acc: 1.0000
Epoch 253/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0016 - acc: 1.0000
Epoch 254/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0016 - acc: 1.0000
Epoc

In [26]:
x_train, y_train, y_train_small = data_genelization(sample_size = 2,loops = 1000, size = 3, key = 1, x_as_vector = False, y_as_vector = False)

In [54]:
 # assume that we have got our data x_train y_train
# now we are going to train it in our model

model = Sequential()
model.add(Dense(4, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [55]:
model.fit(x_train,y_train,epochs = 150)

Epoch 1/150
1000/1000 [==============================] - 0s 496us/step - loss: 0.7594 - acc: 0.4820
Epoch 2/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.7296 - acc: 0.5332
Epoch 3/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.7035 - acc: 0.5535
Epoch 4/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6809 - acc: 0.5798
Epoch 5/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6600 - acc: 0.6430
Epoch 6/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6408 - acc: 0.6497
Epoch 7/150
1000/1000 [==============================] - 0s 25us/step - loss: 0.6226 - acc: 0.6707
Epoch 8/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6050 - acc: 0.6878
Epoch 9/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.5878 - acc: 0.7015
Epoch 10/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.5706 - acc: 0.7185
Epoch 11

1000/1000 [==============================] - 0s 27us/step - loss: 0.0817 - acc: 0.9805
Epoch 84/150
1000/1000 [==============================] - 0s 26us/step - loss: 0.0798 - acc: 0.9805
Epoch 85/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0780 - acc: 0.9805
Epoch 86/150
1000/1000 [==============================] - 0s 25us/step - loss: 0.0763 - acc: 0.9805
Epoch 87/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0746 - acc: 0.9972
Epoch 88/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0730 - acc: 1.0000
Epoch 89/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0714 - acc: 1.0000
Epoch 90/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0698 - acc: 1.0000
Epoch 91/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0683 - acc: 1.0000
Epoch 92/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0669 - acc: 1.0000
Epoch 93/150


In [56]:
model.get_weights()

[array([[ 1.2614266 , -2.1946294 , -1.5446807 ,  1.8021632 ],
        [ 2.7304986 , -0.02158582,  2.2005985 , -0.5643796 ],
        [-0.7911367 ,  0.73573613, -1.8034464 ,  0.28286067],
        [-0.45223793, -1.4599098 ,  0.35353324, -1.505448  ],
        [-2.4287415 ,  1.326423  ,  2.4855835 ,  2.368571  ],
        [ 3.1350098 ,  3.3867607 ,  0.09662584,  1.5484724 ]],
       dtype=float32),
 array([1.674261 , 1.6234328, 1.4496356, 1.221209 ], dtype=float32),
 array([[ 0.52297187, -1.7569    ,  0.43578267, -2.4818363 ,  1.0081764 ,
          0.9765191 ],
        [-0.50075877,  3.203936  , -3.1619108 , -0.61574787,  1.1032968 ,
         -1.5845432 ],
        [ 2.610292  , -1.8877181 , -1.6999984 ,  1.4167665 , -1.3344872 ,
         -0.4839891 ],
        [-2.1381495 , -0.88884467,  2.319683  ,  1.6311033 , -0.59197724,
         -1.642379  ]], dtype=float32),
 array([-2.2643292 ,  0.6654069 ,  0.14345963, -1.4512864 , -3.1625571 ,
         2.3429961 ], dtype=float32)]

In [48]:
model.get_weights()[1]

array([1.3233396, 1.1500345, 1.5411345, 1.7671634], dtype=float32)

In [50]:
model.layers[1].get_weights()

[array([[-0.17041157, -1.3415438 ,  1.0048312 , -2.638664  ,  1.8457879 ,
         -0.17494833],
        [ 2.8886733 , -0.94209313, -2.50845   ,  1.0273534 , -0.8961908 ,
         -0.38473397],
        [-1.0961235 ,  0.7975405 , -0.17514314, -0.7438471 , -2.6763222 ,
          2.6789653 ],
        [-1.288574  ,  2.1119742 , -1.8288964 ,  0.51536745,  0.46846798,
         -1.3760177 ]], dtype=float32),
 array([-2.454229 , -2.5342765,  2.410905 ,  2.4123719, -2.3931627,
        -2.2903526], dtype=float32)]

In [51]:
weights = model.layers[0].get_weights()[0]
biases = model.layers[0].get_weights()[1]

In [52]:
weights

array([[ 1.3632884 , -1.9473228 ,  0.1725147 , -2.4370604 ],
       [ 1.7898074 ,  2.9379802 ,  0.23854892, -1.5549669 ],
       [ 0.50898445, -0.6219571 ,  1.7738153 ,  2.7723904 ],
       [ 1.358545  ,  0.8627558 ,  2.2476776 , -0.2006217 ],
       [-2.6864974 ,  0.7966448 , -1.7154862 ,  0.6694634 ],
       [ 2.6620388 ,  0.12720749, -2.3726258 ,  2.131371  ]],
      dtype=float32)

In [53]:
biases

array([1.3233396, 1.1500345, 1.5411345, 1.7671634], dtype=float32)

In [57]:
model.layers[1].get_weights()

[array([[ 0.52297187, -1.7569    ,  0.43578267, -2.4818363 ,  1.0081764 ,
          0.9765191 ],
        [-0.50075877,  3.203936  , -3.1619108 , -0.61574787,  1.1032968 ,
         -1.5845432 ],
        [ 2.610292  , -1.8877181 , -1.6999984 ,  1.4167665 , -1.3344872 ,
         -0.4839891 ],
        [-2.1381495 , -0.88884467,  2.319683  ,  1.6311033 , -0.59197724,
         -1.642379  ]], dtype=float32),
 array([-2.2643292 ,  0.6654069 ,  0.14345963, -1.4512864 , -3.1625571 ,
         2.3429961 ], dtype=float32)]

In [10]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 20)                1060      
_________________________________________________________________
dense_2 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_3 (Dense)              (None, 52)                1092      
Total params: 2,572
Trainable params: 2,572
Non-trainable params: 0
_________________________________________________________________


In [13]:
from keras.models import Model
#取某一层的输出为输出新建为model，采用函数模型
dense1_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('dense_1').output)
#以这个model的预测值作为输出
dense1_output = dense1_layer_model.predict(x_train)

In [15]:
dense1_output[1]

array([0.4919815 , 2.8937807 , 1.5359185 , 1.8236827 , 0.        ,
       3.5997005 , 0.9909794 , 2.7657804 , 0.24929929, 1.1591802 ,
       2.1862164 , 0.6918705 , 0.53684145, 1.0207528 , 0.19604462,
       1.7340786 , 0.81079715, 0.87367827, 0.9587232 , 0.        ],
      dtype=float32)