In [38]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from myfun import caeserde
from myfun import data_genelization
from myfun import data_test
key = 3
size = 26

In [39]:
help(data_genelization)

Help on function data_genelization in module myfun:

data_genelization(sample_size=2, loops=1000, size=26, key=3, x_as_vector=False, y_as_vector=False)
    data_genelization(sample_size = 2,loops = 1000, size = 26, key = 3, x_as_vector = False, y_as_vector = False):
    return x_train, label with equual size, labels with 1 dimension



In [40]:
# example
x_train, y_train, y_train_small = data_genelization()

In [41]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model
model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [42]:
model.fit(x_train,y_train,epochs = 200)

Epoch 1/200
1000/1000 [==============================] - 0s 399us/step - loss: 0.6636 - acc: 0.7233
Epoch 2/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.5698 - acc: 0.9093
Epoch 3/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.3750 - acc: 0.9589
Epoch 4/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.2051 - acc: 0.9615
Epoch 5/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1683 - acc: 0.9615
Epoch 6/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1643 - acc: 0.9615
Epoch 7/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1625 - acc: 0.9615
Epoch 8/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1611 - acc: 0.9615
Epoch 9/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.1599 - acc: 0.9615
Epoch 10/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1587 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 27us/step - loss: 0.0140 - acc: 0.9967
Epoch 84/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0136 - acc: 0.9968
Epoch 85/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0133 - acc: 0.9968
Epoch 86/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0129 - acc: 0.9969
Epoch 87/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0126 - acc: 0.9971
Epoch 88/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0122 - acc: 0.9972
Epoch 89/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0119 - acc: 0.9973
Epoch 90/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0115 - acc: 0.9972
Epoch 91/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0112 - acc: 0.9974
Epoch 92/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0109 - acc: 0.9976
Epoch 93/200


1000/1000 [==============================] - 0s 26us/step - loss: 0.0012 - acc: 1.0000
Epoch 165/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0012 - acc: 1.0000
Epoch 166/200
1000/1000 [==============================] - 0s 26us/step - loss: 0.0011 - acc: 1.0000
Epoch 167/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0011 - acc: 1.0000
Epoch 168/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.0011 - acc: 1.0000
Epoch 169/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0010 - acc: 1.0000
Epoch 170/200
1000/1000 [==============================] - 0s 27us/step - loss: 9.9955e-04 - acc: 1.0000
Epoch 171/200
1000/1000 [==============================] - 0s 27us/step - loss: 9.7316e-04 - acc: 1.0000
Epoch 172/200
1000/1000 [==============================] - 0s 26us/step - loss: 9.4418e-04 - acc: 1.0000
Epoch 173/200
1000/1000 [==============================] - 0s 26us/step - loss: 9.1985e-04 - 

In [43]:
predictions = model.predict(x_train)

In [44]:
def num2str(index1, index2, size = 26):
    I2L = dict(zip(range(size), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    return ([I2L[index1], I2L[index2]])


def predict_results_only_2(model, x_train, y_train):
    predictions = model.predict(x_train)
    # index1, index2, label1, label2 represent two predictions and two labels respectively
    index1 = np.argmax(predictions[:, 0:26], axis=1)
    index2 = np.argmax(predictions[:, 26:52], axis=1)
    label1 = np.argmax(y_train[:, 0:26], axis=1)
    label2 = np.argmax(y_train[:, 26:52], axis=1)

    # Change number to string and do an output
    prediction_list = list(map(num2str, index1, index2))
    label_list = list(map(num2str, label1, label2))

    return (prediction_list, label_list)


# 理论上只要把矩阵转成字符就好了

In [45]:
def find_diff(list1, list2):   
    if "".join(list1) != "".join(list2):
        return("".join(list1), "".join(list2))
    else:
        return(True)

In [46]:
x_test, y_test, y_test_small = data_genelization()
scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)

1000/1000 [==============================] - 0s 66us/step

acc: 99.65%


In [47]:
# How ever

In [48]:
for i in range(len(prediction_list)):
    print("".join(prediction_list[i]), "".join(label_list[i]))

AU AU
KK KK
UT UT
NH NH
UL UL
ZV ZV
WX WX
OJ OJ
UD UD
AF AF
CM CM
PR PR
MH MH
JF JF
ZX ZX
PX PX
GO GO
IA IA
DX DX
TC TC
BV BV
XK XK
YC YV
PI PI
IH IH
XC XC
WA WA
HQ HQ
AF AF
YC YC
OZ OZ
AC AC
LV LV
ZK ZK
CG CG
GZ GZ
NR NR
WL WL
KN KN
DJ DJ
XT XT
OA OA
ZL ZL
FI FI
UG UG
BA BA
FY FY
MF MF
BY BY
IY IY
BW BW
RS RS
DM DM
EN EN
HE HE
SF SF
FJ FJ
OK OK
XP XP
VY VY
NM NM
AR AR
ST GT
CU CU
OD OD
KK KK
YJ YJ
MR MR
JY JY
EI EI
ST ST
IU IR
ZK ZK
GR GR
IA IA
ZQ ZQ
CH CH
PM PM
WG WG
XI CI
CJ CJ
CZ CZ
OR OR
UE UE
BT BT
GJ GJ
DB DB
YX YX
IY IY
QE QE
JP JP
VF VF
JL JL
VE VE
MR MR
SM SM
OL OL
MQ MQ
FO FO
YQ YQ
EA EA
TD TD
VO VO
IU IR
ZJ ZJ
GP GP
PY PY
DN DN
IP IP
XV XV
YM YM
UK UK
LS LS
JU JU
VN VN
JB JB
KG KG
MD MD
NS NS
RE RE
FO FO
OC OC
JX JX
PU PU
UA UA
NG NG
DP DP
LL LL
KZ KZ
HR HR
XW XW
NR NR
XV XV
FC FC
YE YB
DO DO
IQ IQ
BG BG
YS YS
HR HR
DW AW
XX XX
DO DO
LD HM
RS RS
IW IW
EH EH
LX LX
HG HG
RB RB
UH UH
IQ IQ
ET ET
EV EV
HP HP
FO FO
MI MI
IS IS
YH YH
YQ YQ
AS AS
CO CO
XD XD
VR VR
LI LI
BF BF
IO I

In [56]:
diff = list(map(find_diff, prediction_list, label_list))
output = []
for x in diff:
    if x not in output:
        output.append(x)
output

[True]

In [51]:
temp = ["NC"]
for i in range(1000):
    temp.append("NC")
x_test, y_test, y_test_small = data_test(temp)
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)
diff = list(map(find_diff, prediction_list, label_list))


The accuracy didn't go to 1 but remained at 50% level.(when 26)
Try more training sets.

In [19]:
x_train, y_train, y_train_small = data_genelization(sample_size=3)

In [57]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model

model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [58]:
model.fit(x_train,y_train,epochs = 300)

Epoch 1/300
1000/1000 [==============================] - 0s 422us/step - loss: 0.6738 - acc: 0.6591
Epoch 2/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.5936 - acc: 0.8734
Epoch 3/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.4093 - acc: 0.9553
Epoch 4/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.2206 - acc: 0.9615
Epoch 5/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1716 - acc: 0.9615
Epoch 6/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1659 - acc: 0.9615
Epoch 7/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1631 - acc: 0.9615
Epoch 8/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.1611 - acc: 0.9615
Epoch 9/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1594 - acc: 0.9615
Epoch 10/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.1577 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 26us/step - loss: 0.0088 - acc: 0.9983
Epoch 84/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0085 - acc: 0.9984
Epoch 85/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0082 - acc: 0.9986
Epoch 86/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0079 - acc: 0.9985
Epoch 87/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0075 - acc: 0.9987
Epoch 88/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.0073 - acc: 0.9987
Epoch 89/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0070 - acc: 0.9987
Epoch 90/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0068 - acc: 0.9988
Epoch 91/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0065 - acc: 0.9988
Epoch 92/300
1000/1000 [==============================] - 0s 26us/step - loss: 0.0063 - acc: 0.9989
Epoch 93/300


1000/1000 [==============================] - 0s 26us/step - loss: 6.2402e-04 - acc: 1.0000
Epoch 164/300
1000/1000 [==============================] - 0s 26us/step - loss: 6.0739e-04 - acc: 1.0000
Epoch 165/300
1000/1000 [==============================] - 0s 26us/step - loss: 5.9278e-04 - acc: 1.0000
Epoch 166/300
1000/1000 [==============================] - 0s 26us/step - loss: 5.7500e-04 - acc: 1.0000
Epoch 167/300
1000/1000 [==============================] - 0s 26us/step - loss: 5.5993e-04 - acc: 1.0000
Epoch 168/300
1000/1000 [==============================] - 0s 27us/step - loss: 5.4504e-04 - acc: 1.0000
Epoch 169/300
1000/1000 [==============================] - 0s 26us/step - loss: 5.3135e-04 - acc: 1.0000
Epoch 170/300
1000/1000 [==============================] - 0s 26us/step - loss: 5.1789e-04 - acc: 1.0000
Epoch 171/300
1000/1000 [==============================] - 0s 27us/step - loss: 5.0478e-04 - acc: 1.0000
Epoch 172/300
1000/1000 [==============================] - 0s 26us/st

1000/1000 [==============================] - 0s 32us/step - loss: 9.7727e-05 - acc: 1.0000
Epoch 242/300
1000/1000 [==============================] - 0s 28us/step - loss: 9.5864e-05 - acc: 1.0000
Epoch 243/300
1000/1000 [==============================] - 0s 26us/step - loss: 9.3756e-05 - acc: 1.0000
Epoch 244/300
1000/1000 [==============================] - 0s 26us/step - loss: 9.1729e-05 - acc: 1.0000
Epoch 245/300
1000/1000 [==============================] - 0s 26us/step - loss: 8.9742e-05 - acc: 1.0000
Epoch 246/300
1000/1000 [==============================] - 0s 26us/step - loss: 8.7764e-05 - acc: 1.0000
Epoch 247/300
1000/1000 [==============================] - 0s 27us/step - loss: 8.6466e-05 - acc: 1.0000
Epoch 248/300
1000/1000 [==============================] - 0s 27us/step - loss: 8.4592e-05 - acc: 1.0000
Epoch 249/300
1000/1000 [==============================] - 0s 29us/step - loss: 8.2307e-05 - acc: 1.0000
Epoch 250/300
1000/1000 [==============================] - 0s 32us/st

In [59]:
x_train, y_train, y_train_small = data_genelization(sample_size = 2,loops = 1000, size = 3, key = 1, x_as_vector = False, y_as_vector = False)

In [60]:
 # assume that we have got our data x_train y_train
# now we are going to train it in our model

model = Sequential()
model.add(Dense(4, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [61]:
model.fit(x_train,y_train,epochs = 150)

Epoch 1/150
1000/1000 [==============================] - 0s 310us/step - loss: 0.7359 - acc: 0.5187
Epoch 2/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.7086 - acc: 0.5650
Epoch 3/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.6845 - acc: 0.5883
Epoch 4/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.6636 - acc: 0.6147
Epoch 5/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.6445 - acc: 0.6573
Epoch 6/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.6260 - acc: 0.6962
Epoch 7/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.6085 - acc: 0.7107
Epoch 8/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.5916 - acc: 0.7370
Epoch 9/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.5728 - acc: 0.7477
Epoch 10/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.5533 - acc: 0.7797
Epoch 11

1000/1000 [==============================] - 0s 23us/step - loss: 0.0730 - acc: 1.0000
Epoch 84/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0714 - acc: 1.0000
Epoch 85/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0699 - acc: 1.0000
Epoch 86/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0684 - acc: 1.0000
Epoch 87/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0669 - acc: 1.0000
Epoch 88/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0655 - acc: 1.0000
Epoch 89/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0641 - acc: 1.0000
Epoch 90/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0627 - acc: 1.0000
Epoch 91/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0614 - acc: 1.0000
Epoch 92/150
1000/1000 [==============================] - 0s 22us/step - loss: 0.0600 - acc: 1.0000
Epoch 93/150


In [56]:
model.get_weights()

[array([[ 1.2614266 , -2.1946294 , -1.5446807 ,  1.8021632 ],
        [ 2.7304986 , -0.02158582,  2.2005985 , -0.5643796 ],
        [-0.7911367 ,  0.73573613, -1.8034464 ,  0.28286067],
        [-0.45223793, -1.4599098 ,  0.35353324, -1.505448  ],
        [-2.4287415 ,  1.326423  ,  2.4855835 ,  2.368571  ],
        [ 3.1350098 ,  3.3867607 ,  0.09662584,  1.5484724 ]],
       dtype=float32),
 array([1.674261 , 1.6234328, 1.4496356, 1.221209 ], dtype=float32),
 array([[ 0.52297187, -1.7569    ,  0.43578267, -2.4818363 ,  1.0081764 ,
          0.9765191 ],
        [-0.50075877,  3.203936  , -3.1619108 , -0.61574787,  1.1032968 ,
         -1.5845432 ],
        [ 2.610292  , -1.8877181 , -1.6999984 ,  1.4167665 , -1.3344872 ,
         -0.4839891 ],
        [-2.1381495 , -0.88884467,  2.319683  ,  1.6311033 , -0.59197724,
         -1.642379  ]], dtype=float32),
 array([-2.2643292 ,  0.6654069 ,  0.14345963, -1.4512864 , -3.1625571 ,
         2.3429961 ], dtype=float32)]

In [48]:
model.get_weights()[1]

array([1.3233396, 1.1500345, 1.5411345, 1.7671634], dtype=float32)

In [50]:
model.layers[1].get_weights()

[array([[-0.17041157, -1.3415438 ,  1.0048312 , -2.638664  ,  1.8457879 ,
         -0.17494833],
        [ 2.8886733 , -0.94209313, -2.50845   ,  1.0273534 , -0.8961908 ,
         -0.38473397],
        [-1.0961235 ,  0.7975405 , -0.17514314, -0.7438471 , -2.6763222 ,
          2.6789653 ],
        [-1.288574  ,  2.1119742 , -1.8288964 ,  0.51536745,  0.46846798,
         -1.3760177 ]], dtype=float32),
 array([-2.454229 , -2.5342765,  2.410905 ,  2.4123719, -2.3931627,
        -2.2903526], dtype=float32)]

In [51]:
weights = model.layers[0].get_weights()[0]
biases = model.layers[0].get_weights()[1]

In [52]:
weights

array([[ 1.3632884 , -1.9473228 ,  0.1725147 , -2.4370604 ],
       [ 1.7898074 ,  2.9379802 ,  0.23854892, -1.5549669 ],
       [ 0.50898445, -0.6219571 ,  1.7738153 ,  2.7723904 ],
       [ 1.358545  ,  0.8627558 ,  2.2476776 , -0.2006217 ],
       [-2.6864974 ,  0.7966448 , -1.7154862 ,  0.6694634 ],
       [ 2.6620388 ,  0.12720749, -2.3726258 ,  2.131371  ]],
      dtype=float32)

In [53]:
biases

array([1.3233396, 1.1500345, 1.5411345, 1.7671634], dtype=float32)

In [57]:
model.layers[1].get_weights()

[array([[ 0.52297187, -1.7569    ,  0.43578267, -2.4818363 ,  1.0081764 ,
          0.9765191 ],
        [-0.50075877,  3.203936  , -3.1619108 , -0.61574787,  1.1032968 ,
         -1.5845432 ],
        [ 2.610292  , -1.8877181 , -1.6999984 ,  1.4167665 , -1.3344872 ,
         -0.4839891 ],
        [-2.1381495 , -0.88884467,  2.319683  ,  1.6311033 , -0.59197724,
         -1.642379  ]], dtype=float32),
 array([-2.2643292 ,  0.6654069 ,  0.14345963, -1.4512864 , -3.1625571 ,
         2.3429961 ], dtype=float32)]

In [10]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 20)                1060      
_________________________________________________________________
dense_2 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_3 (Dense)              (None, 52)                1092      
Total params: 2,572
Trainable params: 2,572
Non-trainable params: 0
_________________________________________________________________


In [13]:
from keras.models import Model
#取某一层的输出为输出新建为model，采用函数模型
dense1_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('dense_1').output)
#以这个model的预测值作为输出
dense1_output = dense1_layer_model.predict(x_train)

In [15]:
dense1_output[1]

array([0.4919815 , 2.8937807 , 1.5359185 , 1.8236827 , 0.        ,
       3.5997005 , 0.9909794 , 2.7657804 , 0.24929929, 1.1591802 ,
       2.1862164 , 0.6918705 , 0.53684145, 1.0207528 , 0.19604462,
       1.7340786 , 0.81079715, 0.87367827, 0.9587232 , 0.        ],
      dtype=float32)

In [18]:
x_train

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])