In [94]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from myfun import caeserde
from myfun import data_genelization
from myfun import data_test
key = 3
size = 26

In [95]:
help(data_genelization)

Help on function data_genelization in module myfun:

data_genelization(sample_size=2, loops=1000, size=26, key=3, x_as_vector=False, y_as_vector=False)
    data_genelization(sample_size = 2,loops = 1000, size = 26, key = 3, x_as_vector = False, y_as_vector = False):
    return x_train, label with equual size, labels with 1 dimension



In [96]:
# example
x_train, y_train, y_train_small = data_genelization()

In [97]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model
model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [98]:
model.fit(x_train,y_train,epochs = 200)

Epoch 1/200
1000/1000 [==============================] - 0s 424us/step - loss: 0.6710 - acc: 0.7043
Epoch 2/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.5927 - acc: 0.8943
Epoch 3/200
1000/1000 [==============================] - 0s 34us/step - loss: 0.4116 - acc: 0.9590
Epoch 4/200
1000/1000 [==============================] - 0s 34us/step - loss: 0.2240 - acc: 0.9615
Epoch 5/200
1000/1000 [==============================] - 0s 31us/step - loss: 0.1729 - acc: 0.9615
Epoch 6/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.1662 - acc: 0.9615
Epoch 7/200
1000/1000 [==============================] - 0s 35us/step - loss: 0.1629 - acc: 0.9615
Epoch 8/200
1000/1000 [==============================] - 0s 34us/step - loss: 0.1606 - acc: 0.9615
Epoch 9/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.1587 - acc: 0.9615
Epoch 10/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1570 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 29us/step - loss: 0.0111 - acc: 0.9977
Epoch 84/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0107 - acc: 0.9979
Epoch 85/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0103 - acc: 0.9979
Epoch 86/200
1000/1000 [==============================] - 0s 33us/step - loss: 0.0099 - acc: 0.9980
Epoch 87/200
1000/1000 [==============================] - 0s 31us/step - loss: 0.0096 - acc: 0.9981
Epoch 88/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0092 - acc: 0.9983
Epoch 89/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0089 - acc: 0.9983
Epoch 90/200
1000/1000 [==============================] - 0s 31us/step - loss: 0.0086 - acc: 0.9983
Epoch 91/200
1000/1000 [==============================] - 0s 30us/step - loss: 0.0083 - acc: 0.9985
Epoch 92/200
1000/1000 [==============================] - 0s 32us/step - loss: 0.0080 - acc: 0.9986
Epoch 93/200


1000/1000 [==============================] - 0s 27us/step - loss: 8.0689e-04 - acc: 1.0000
Epoch 165/200
1000/1000 [==============================] - 0s 30us/step - loss: 7.8267e-04 - acc: 1.0000
Epoch 166/200
1000/1000 [==============================] - 0s 27us/step - loss: 7.6363e-04 - acc: 1.0000
Epoch 167/200
1000/1000 [==============================] - 0s 31us/step - loss: 7.4519e-04 - acc: 1.0000
Epoch 168/200
1000/1000 [==============================] - 0s 34us/step - loss: 7.2382e-04 - acc: 1.0000
Epoch 169/200
1000/1000 [==============================] - 0s 27us/step - loss: 7.0438e-04 - acc: 1.0000
Epoch 170/200
1000/1000 [==============================] - 0s 27us/step - loss: 6.8432e-04 - acc: 1.0000
Epoch 171/200
1000/1000 [==============================] - 0s 30us/step - loss: 6.6783e-04 - acc: 1.0000
Epoch 172/200
1000/1000 [==============================] - 0s 26us/step - loss: 6.4961e-04 - acc: 1.0000
Epoch 173/200
1000/1000 [==============================] - 0s 27us/st

In [99]:
predictions = model.predict(x_train)

In [100]:
def num2str(index1, index2, size = 26):
    I2L = dict(zip(range(size), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    return ([I2L[index1], I2L[index2]])


def predict_results_only_2(model, x_train, y_train):
    predictions = model.predict(x_train)
    # index1, index2, label1, label2 represent two predictions and two labels respectively
    index1 = np.argmax(predictions[:, 0:26], axis=1)
    index2 = np.argmax(predictions[:, 26:52], axis=1)
    label1 = np.argmax(y_train[:, 0:26], axis=1)
    label2 = np.argmax(y_train[:, 26:52], axis=1)

    # Change number to string and do an output
    prediction_list = list(map(num2str, index1, index2))
    label_list = list(map(num2str, label1, label2))

    return (prediction_list, label_list)


# 理论上只要把矩阵转成字符就好了

In [101]:
def find_diff(list1, list2):
    if "".join(list1) != "".join(list2):
        print("".join(list1), "".join(list2))
        return("".join(list1), "".join(list2))
    else:
        return(True)

In [102]:
x_test, y_test, y_test_small = data_genelization()
scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)

for i in range(len(prediction_list)):
    print("".join(prediction_list[i]), "".join(label_list[i]))

1000/1000 [==============================] - 0s 73us/step

acc: 99.68%
UZ UZ
UL UL
VU VU
KV KV
GW GW
NF NF
HL HL
GE GE
HA HA
XB XB
MK MK
AY AY
NE NE
IN IN
SJ SJ
PC PC
AN AN
TE TE
PK PK
UE UE
QI QI
AI AI
NB NB
OM IR
CL CL
JV JV
BY BY
RP RP
YL YL
ZF ZF
IK IK
ML ML
NV NV
UC UC
NW NW
HY HY
TM TM
UR UR
ZV ZV
YC YC
SY SY
QI QI
BK BK
OG OG
DN DN
XD JE
RF RF
PD PD
QQ QQ
NM NM
XE XE
KF KF
MY MY
QQ QQ
CF CF
YC YC
KA KS
MZ MZ
ES ES
ZZ ZZ
KA KA
AN AN
CX CX
FA FA
DB DB
QM QM
VN VN
YS YS
MT MT
SE SE
TS TS
CF CF
DH DH
CO CO
PF PF
YD YD
ZB ZB
OC XA
HM HM
FC FC
XX XX
NP NP
MC MC
OE OE
AT AT
IT IT
LJ LJ
PT PT
LG LG
MK MK
WA WA
DW DW
BU BU
OZ OZ
IP IP
OD OD
XQ XQ
JU JU
PS PS
OI OI
JX JX
TA TA
KC KC
WX WX
DO DO
XG XG
HB HB
ZI ZI
EY EY
JF JF
VX VX
RU RU
YM YM
FH FH
DJ DJ
LS LS
RL RL
HZ HZ
QY QY
WB WB
OI OI
EI EI
RZ RZ
EJ EJ
SK SK
HI HI
EP EP
YV YV
CT CT
LG LK
DS DS
TE TE
XS XS
MN MN
HN HN
GU GS
SG SG
VH VH
ED ED
XL XL
NU LU
CO CO
YM YM
JP JP
BZ BZ
YE YE
FW FW
AO AO
UT UT
BQ BQ
UX UX
ZO ZO
NV NV
BJ BJ
IS IS

In [103]:
diff = list(map(find_diff, prediction_list, label_list))
diff[i]

OM IR
XD JE
KA KS
OC XA
LG LK
GU GS
NU LU
LG LK
GU GS
VP VK
ZQ ZM
WG HT
HO WO
WX JN
LG LK
PP YP
ZP DP
VP VK
WG HT
MC KW
NG NA
NS NX
UV UU
PP YP
PP YP
OC XA
PP YP
WX JN
HO WO
NU LU


True

In [104]:
temp = ["NC"]
for i in range(1000):
    temp.append("NC")
x_test, y_test, y_test_small = data_test(temp)
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)
diff = list(map(find_diff, prediction_list, label_list))


In [105]:
diff

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,

The accuracy didn't go to 1 but remained at 50% level.(when 26)
Try more training sets.

In [106]:
x_train, y_train, y_train_small = data_genelization(sample_size=3)

In [107]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model

model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [108]:
model.fit(x_train,y_train,epochs = 300)

Epoch 1/300
1000/1000 [==============================] - 0s 355us/step - loss: 0.6605 - acc: 0.7376
Epoch 2/300
1000/1000 [==============================] - 0s 35us/step - loss: 0.5386 - acc: 0.9307
Epoch 3/300
1000/1000 [==============================] - 0s 34us/step - loss: 0.3100 - acc: 0.9613
Epoch 4/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.1824 - acc: 0.9615
Epoch 5/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.1669 - acc: 0.9615
Epoch 6/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.1643 - acc: 0.9615
Epoch 7/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.1627 - acc: 0.9615
Epoch 8/300
1000/1000 [==============================] - 0s 35us/step - loss: 0.1614 - acc: 0.9615
Epoch 9/300
1000/1000 [==============================] - 0s 33us/step - loss: 0.1604 - acc: 0.9615
Epoch 10/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.1594 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 28us/step - loss: 0.0360 - acc: 0.9889
Epoch 84/300
1000/1000 [==============================] - 0s 30us/step - loss: 0.0353 - acc: 0.9893
Epoch 85/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0346 - acc: 0.9897
Epoch 86/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0339 - acc: 0.9899
Epoch 87/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0332 - acc: 0.9902
Epoch 88/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0326 - acc: 0.9902
Epoch 89/300
1000/1000 [==============================] - 0s 32us/step - loss: 0.0319 - acc: 0.9904
Epoch 90/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0312 - acc: 0.9908
Epoch 91/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0307 - acc: 0.9911
Epoch 92/300
1000/1000 [==============================] - 0s 32us/step - loss: 0.0301 - acc: 0.9912
Epoch 93/300


1000/1000 [==============================] - 0s 28us/step - loss: 0.0087 - acc: 0.9986
Epoch 165/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0085 - acc: 0.9984
Epoch 166/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0084 - acc: 0.9986
Epoch 167/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0082 - acc: 0.9987
Epoch 168/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0081 - acc: 0.9985
Epoch 169/300
1000/1000 [==============================] - 0s 36us/step - loss: 0.0079 - acc: 0.9987
Epoch 170/300
1000/1000 [==============================] - 0s 34us/step - loss: 0.0078 - acc: 0.9987
Epoch 171/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0077 - acc: 0.9988
Epoch 172/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0075 - acc: 0.9987
Epoch 173/300
1000/1000 [==============================] - 0s 32us/step - loss: 0.0074 - acc: 0.9988
Epoc

1000/1000 [==============================] - 0s 31us/step - loss: 0.0020 - acc: 1.0000
Epoch 246/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0020 - acc: 0.9999
Epoch 247/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0019 - acc: 0.9999
Epoch 248/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0019 - acc: 1.0000
Epoch 249/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0019 - acc: 1.0000
Epoch 250/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0018 - acc: 1.0000
Epoch 251/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0018 - acc: 1.0000
Epoch 252/300
1000/1000 [==============================] - 0s 27us/step - loss: 0.0018 - acc: 1.0000
Epoch 253/300
1000/1000 [==============================] - 0s 35us/step - loss: 0.0017 - acc: 1.0000
Epoch 254/300
1000/1000 [==============================] - 0s 32us/step - loss: 0.0017 - acc: 1.0000
Epoc

In [127]:
x_train, y_train, y_train_small = data_genelization(sample_size = 2,loops = 10000, size = 3, key = 1, x_as_vector = False, y_as_vector = False)

In [153]:
 # assume that we have got our data x_train y_train
# now we are going to train it in our model

model = Sequential()
model.add(Dense(4, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [154]:
model.fit(x_train,y_train,epochs = 10)

Epoch 1/10
10000/10000 [==============================] - 1s 66us/step - loss: 0.6555 - acc: 0.6667
Epoch 2/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.5025 - acc: 0.6926
Epoch 3/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.4092 - acc: 0.7230
Epoch 4/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.3497 - acc: 0.7206
Epoch 5/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.3000 - acc: 0.7076
Epoch 6/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.2709 - acc: 0.7192
Epoch 7/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.2564 - acc: 0.7295
Epoch 8/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.2485 - acc: 0.7270
Epoch 9/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.2439 - acc: 0.7140
Epoch 10/10
10000/10000 [==============================] - 0s 22us/step - loss: 0.2409 - acc: 0.7055

In [132]:
model.get_weights()

[array([[ 1.5685940e+00, -7.5578344e-01,  2.9726129e+00,  2.8926406e-02],
        [-6.4602363e-01, -1.3272898e+00, -1.6753883e+00,  8.8879782e-01],
        [ 2.8905544e-01,  2.7274203e+00, -4.1011357e-01,  1.4950769e+00],
        [-1.3924526e+00,  4.8229340e-01,  1.2612160e+00, -2.0509748e+00],
        [-7.5499356e-01, -2.2950272e-01,  1.1744325e+00,  1.8901294e+00],
        [ 2.3575439e+00,  8.6360145e-04, -5.5712640e-01, -1.1779923e+00]],
       dtype=float32),
 array([1.5374192, 1.1142339, 1.0893863, 1.1623676], dtype=float32),
 array([[-0.13530163, -0.6692685 ,  0.12882563, -1.424377  ,  1.9253594 ,
         -2.1576288 ],
        [-1.4458797 ,  2.652958  , -1.4707116 , -1.4061795 , -0.41814592,
          1.441015  ],
        [-1.1648395 , -1.4701993 ,  1.5168785 ,  0.04260638, -1.8375388 ,
          1.301559  ],
        [ 0.4505602 , -0.20008475, -0.8927824 ,  2.7003853 , -1.1340812 ,
         -2.3374708 ]], dtype=float32),
 array([ 1.884285 , -1.6483525, -1.9364004, -1.4228922, -0

In [133]:
model.get_weights()[1]

array([1.5374192, 1.1142339, 1.0893863, 1.1623676], dtype=float32)

In [134]:
model.layers[1].get_weights()

[array([[-0.13530163, -0.6692685 ,  0.12882563, -1.424377  ,  1.9253594 ,
         -2.1576288 ],
        [-1.4458797 ,  2.652958  , -1.4707116 , -1.4061795 , -0.41814592,
          1.441015  ],
        [-1.1648395 , -1.4701993 ,  1.5168785 ,  0.04260638, -1.8375388 ,
          1.301559  ],
        [ 0.4505602 , -0.20008475, -0.8927824 ,  2.7003853 , -1.1340812 ,
         -2.3374708 ]], dtype=float32),
 array([ 1.884285 , -1.6483525, -1.9364004, -1.4228922, -0.187781 ,
         0.6112278], dtype=float32)]

In [135]:
weights = model.layers[0].get_weights()[0]
biases = model.layers[0].get_weights()[1]

In [136]:
weights

array([[ 1.5685940e+00, -7.5578344e-01,  2.9726129e+00,  2.8926406e-02],
       [-6.4602363e-01, -1.3272898e+00, -1.6753883e+00,  8.8879782e-01],
       [ 2.8905544e-01,  2.7274203e+00, -4.1011357e-01,  1.4950769e+00],
       [-1.3924526e+00,  4.8229340e-01,  1.2612160e+00, -2.0509748e+00],
       [-7.5499356e-01, -2.2950272e-01,  1.1744325e+00,  1.8901294e+00],
       [ 2.3575439e+00,  8.6360145e-04, -5.5712640e-01, -1.1779923e+00]],
      dtype=float32)

In [53]:
biases

array([1.3233396, 1.1500345, 1.5411345, 1.7671634], dtype=float32)

In [57]:
model.layers[1].get_weights()

[array([[ 0.52297187, -1.7569    ,  0.43578267, -2.4818363 ,  1.0081764 ,
          0.9765191 ],
        [-0.50075877,  3.203936  , -3.1619108 , -0.61574787,  1.1032968 ,
         -1.5845432 ],
        [ 2.610292  , -1.8877181 , -1.6999984 ,  1.4167665 , -1.3344872 ,
         -0.4839891 ],
        [-2.1381495 , -0.88884467,  2.319683  ,  1.6311033 , -0.59197724,
         -1.642379  ]], dtype=float32),
 array([-2.2643292 ,  0.6654069 ,  0.14345963, -1.4512864 , -3.1625571 ,
         2.3429961 ], dtype=float32)]

In [138]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 4)                 28        
_________________________________________________________________
dense_23 (Dense)             (None, 6)                 30        
Total params: 58
Trainable params: 58
Non-trainable params: 0
_________________________________________________________________


In [139]:
from keras.models import Model
#取某一层的输出为输出新建为model，采用函数模型
dense1_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('dense_22').output)

#以这个model的预测值作为输出
dense1_output = dense1_layer_model.predict(x_train)

In [140]:
dense1_output[1]

array([1.0714811, 3.6121516, 1.8537053, 4.547574 ], dtype=float32)

In [144]:
dense2_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('dense_23').output)

In [145]:
dense2_output = dense2_layer_model.predict(x_train)

In [152]:
dense2_output[1]

array([2.6759535e-02, 9.7293854e-01, 2.3421645e-04, 9.8701334e-01,
       2.7492642e-04, 8.9016557e-03], dtype=float32)

In [ ]:
Obviously, for this model, softmax function cannot get a good result!

In [156]:

model = Sequential()
model.add(Dense(4, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(y_train.shape[1], activation='softmax'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train,y_train,epochs = 20)

Epoch 1/20
10000/10000 [==============================] - 1s 76us/step - loss: 0.6292 - acc: 0.6694
Epoch 2/20
10000/10000 [==============================] - 0s 24us/step - loss: 0.4786 - acc: 0.7031
Epoch 3/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.3667 - acc: 0.7187
Epoch 4/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.3080 - acc: 0.7211
Epoch 5/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2794 - acc: 0.7162
Epoch 6/20
10000/10000 [==============================] - 0s 22us/step - loss: 0.2631 - acc: 0.6989
Epoch 7/20
10000/10000 [==============================] - 0s 22us/step - loss: 0.2531 - acc: 0.7017
Epoch 8/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2466 - acc: 0.6973
Epoch 9/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2422 - acc: 0.7071
Epoch 10/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2392 - acc: 0.7162

In [159]:
model.fit(x_train,y_train,epochs = 20)

Epoch 1/20
10000/10000 [==============================] - 0s 26us/step - loss: 0.2311 - acc: 0.8297
Epoch 2/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8327
Epoch 3/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8025
Epoch 4/20
10000/10000 [==============================] - 0s 27us/step - loss: 0.2311 - acc: 0.7930
Epoch 5/20
10000/10000 [==============================] - 0s 24us/step - loss: 0.2311 - acc: 0.8062
Epoch 6/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8316
Epoch 7/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8302
Epoch 8/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8235
Epoch 9/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8320
Epoch 10/20
10000/10000 [==============================] - 0s 23us/step - loss: 0.2311 - acc: 0.8149

In [22]:
import random
import string
loops =10000
size =26
sample_size =2
temp = ''.join(random.choices(string.ascii_uppercase[0:size], k = loops*sample_size))

In [76]:
%%time
from myfun import misslabeled_data_genelization
misslabeled_data_genelization(loops=10000,prob=1)

CPU times: user 24.4 s, sys: 8.99 s, total: 33.4 s
Wall time: 7.63 s


[0, 20]

In [115]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation=’relu’, input_shape=(2,56,1)))
model.add(Conv2D(32, kernel_size=3, activation=’relu’))
model.add(Flatten())
model.add(Dense(10, activation=’softmax’))


SyntaxError: invalid character in identifier (<ipython-input-115-3a148efc50c6>, line 6)