In [63]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from myfun import caeserde
from myfun import data_genelization
from myfun import data_test
key = 3
size = 26

In [64]:
help(data_genelization)

Help on function data_genelization in module myfun:

data_genelization(sample_size=2, loops=1000, size=26, key=3, x_as_vector=False, y_as_vector=False)
    data_genelization(sample_size = 2,loops = 1000, size = 26, key = 3, x_as_vector = False, y_as_vector = False):
    return x_train, label with equual size, labels with 1 dimension



In [65]:
# example
x_train, y_train, y_train_small = data_genelization()

In [66]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model
model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [67]:
model.fit(x_train,y_train,epochs = 200)

Epoch 1/200
1000/1000 [==============================] - 0s 465us/step - loss: 0.6700 - acc: 0.6623
Epoch 2/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.5888 - acc: 0.8702
Epoch 3/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.4076 - acc: 0.9510
Epoch 4/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.2146 - acc: 0.9615
Epoch 5/200
1000/1000 [==============================] - 0s 29us/step - loss: 0.1666 - acc: 0.9615
Epoch 6/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1618 - acc: 0.9615
Epoch 7/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.1595 - acc: 0.9615
Epoch 8/200
1000/1000 [==============================] - 0s 30us/step - loss: 0.1579 - acc: 0.9615
Epoch 9/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.1563 - acc: 0.9615
Epoch 10/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.1548 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 27us/step - loss: 0.0089 - acc: 0.9985
Epoch 84/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0086 - acc: 0.9985
Epoch 85/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0083 - acc: 0.9986
Epoch 86/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0080 - acc: 0.9987
Epoch 87/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.0077 - acc: 0.9986
Epoch 88/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.0074 - acc: 0.9988
Epoch 89/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0072 - acc: 0.9988
Epoch 90/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0070 - acc: 0.9989
Epoch 91/200
1000/1000 [==============================] - 0s 28us/step - loss: 0.0067 - acc: 0.9988
Epoch 92/200
1000/1000 [==============================] - 0s 27us/step - loss: 0.0065 - acc: 0.9990
Epoch 93/200


In [83]:
predictions = model.predict(x_train)

In [69]:
def num2str(index1, index2, size = 26):
    I2L = dict(zip(range(size), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    return ([I2L[index1], I2L[index2]])


def predict_results_only_2(model, x_train, y_train):
    predictions = model.predict(x_train)
    # index1, index2, label1, label2 represent two predictions and two labels respectively
    index1 = np.argmax(predictions[:, 0:26], axis=1)
    index2 = np.argmax(predictions[:, 26:52], axis=1)
    label1 = np.argmax(y_train[:, 0:26], axis=1)
    label2 = np.argmax(y_train[:, 26:52], axis=1)

    # Change number to string and do an output
    prediction_list = list(map(num2str, index1, index2))
    label_list = list(map(num2str, label1, label2))

    return (prediction_list, label_list)

In [70]:
def find_diff(list1, list2):   
    if "".join(list1) != "".join(list2):
        return("".join(list1), "".join(list2))
    else:
        return(True)

In [71]:
x_test, y_test, y_test_small = data_genelization()
scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)

1000/1000 [==============================] - 0s 100us/step

acc: 99.62%


In [72]:
for i in range(len(prediction_list)):
    print("".join(prediction_list[i]), "".join(label_list[i]))

UN UN
YG YG
LW LW
KG KG
IC IC
DV DV
IM IM
CF CF
SV SV
VR VR
EK EK
DY DY
PJ PJ
NM NM
FD FD
GR GR
CK CK
FG FG
VK VX
RF RF
FG FG
WM QC
IC IC
WR WR
AM AM
VP VP
LY LY
UB UB
IM IM
WG WG
GM GM
JI JI
BS BS
EI EI
AJ AJ
MY MY
JW JW
LQ LQ
LR LR
AB AB
WS WS
KR KR
JM JM
MV MV
SQ XQ
LW LW
GL GL
VS VS
AF AF
HC HC
CC CC
FK FK
RW RW
ZU ZU
FI FI
KL KL
VE VE
DO DO
GG GG
JV JV
SY SY
SP SP
NB NB
KX KX
CP CP
TN TN
LJ LJ
TQ TQ
GI GI
NT NT
SQ SQ
YY YY
LG LG
NY NY
FC FC
EY EY
OT OT
WS WS
BG BG
OU OU
MZ MZ
KF KF
IP IP
FB FB
YN YN
FA FA
RE RE
XA XA
XI XI
EI EI
RF RF
AT AT
CG CG
GD GD
WX WX
ZX ZX
QE QE
XC XC
YN YN
XM XM
CF CF
NL NL
HS HS
NX NX
EO EO
IP IP
SP SP
LH LH
MM MM
CP CP
LX LX
ZU ZU
XS XS
GV GV
TN TN
NM NM
VC VC
FD FD
CX CX
PY PY
XR XR
AS AS
ZK ZK
FF FF
ZP ZP
UF UF
MO MO
HM HM
FE EZ
ZD ZD
OQ OQ
IP IP
RU RU
JY JY
RP RP
RI RI
UE UE
UK UK
WK WK
JQ JQ
BS BS
ES ES
QS QS
RT RT
EA EA
QJ QJ
MO MO
UO RX
CK CK
VD VD
SQ SQ
VB VB
OU OL
RL RL
DD DD
EV EV
BW BW
ZW ZW
UN UN
HC HC
QH QH
AE AE
MU MU
VP VP
BO BO
RM RM
KC K

In [73]:
diff = list(map(find_diff, prediction_list, label_list))
output = []
for x in diff:
    if x not in output:
        output.append(x)
output

[True,
 ('VK', 'VX'),
 ('WM', 'QC'),
 ('SQ', 'XQ'),
 ('FE', 'EZ'),
 ('UO', 'RX'),
 ('OU', 'OL'),
 ('TG', 'ZC'),
 ('VT', 'YT'),
 ('GC', 'GX'),
 ('SO', 'ZO'),
 ('TL', 'PK'),
 ('LL', 'SL'),
 ('HL', 'HU'),
 ('OG', 'OS'),
 ('HC', 'DS'),
 ('UE', 'CQ'),
 ('HD', 'WD'),
 ('SA', 'SH')]

Pick an error see if the model can predict it well or not.

In [79]:
temp = ["SA"]
for i in range(1000):
    temp.append("SA")
x_test, y_test, y_test_small = data_test(temp)
prediction_list, label_list = predict_results_only_2(model, x_test, y_test)
diff = list(map(find_diff, prediction_list, label_list))
output = []
for x in diff:
    if x not in output:
        output.append(x)
output

[True]

## For 3 letters

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from myfun import caeserde
from myfun import data_genelization
from myfun import data_test
key = 3
size = 26

Using TensorFlow backend.


As 3 letters have 17576 different combinations, we set the for loop times to 20000.

In [37]:
# example
x_train, y_train, y_train_small = data_genelization(sample_size = 3, loops = 20000)

In [40]:
# assume that we have got our data x_train y_train
# now we are going to train it in our model
model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [41]:
model.fit(x_train,y_train,epochs = 20)

Epoch 1/20
20000/20000 [==============================] - 1s 42us/step - loss: 0.2133 - acc: 0.9441
Epoch 2/20
20000/20000 [==============================] - 1s 29us/step - loss: 0.1243 - acc: 0.9621
Epoch 3/20
20000/20000 [==============================] - 1s 28us/step - loss: 0.0866 - acc: 0.9695
Epoch 4/20
20000/20000 [==============================] - 1s 27us/step - loss: 0.0629 - acc: 0.9783
Epoch 5/20
20000/20000 [==============================] - 1s 29us/step - loss: 0.0479 - acc: 0.9841
Epoch 6/20
20000/20000 [==============================] - 1s 29us/step - loss: 0.0368 - acc: 0.9882
Epoch 7/20
20000/20000 [==============================] - 1s 27us/step - loss: 0.0277 - acc: 0.9914
Epoch 8/20
20000/20000 [==============================] - 1s 27us/step - loss: 0.0202 - acc: 0.9941
Epoch 9/20
20000/20000 [==============================] - 1s 27us/step - loss: 0.0140 - acc: 0.9963
Epoch 10/20
20000/20000 [==============================] - 1s 27us/step - loss: 0.0090 - acc: 0.9979

In [42]:
predictions = model.predict(x_train)

In [43]:
def num2str(index1, index2, index3, size = 26):
    I2L = dict(zip(range(size), "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    return ([I2L[index1], I2L[index2], I2L[index3]])


def predict_results_only_3(model, x_train, y_train):
    predictions = model.predict(x_train)
    # index1, index2, label1, label2 represent two predictions and two labels respectively
    index1 = np.argmax(predictions[:, 0:26], axis=1)
    index2 = np.argmax(predictions[:, 26:52], axis=1)
    index3 = np.argmax(predictions[:, 52:-1], axis=1)
    label1 = np.argmax(y_train[:, 0:26], axis=1)
    label2 = np.argmax(y_train[:, 26:52], axis=1)
    label3 = np.argmax(y_train[:, 52:-1], axis=1)

    # Change number to string and do an output
    prediction_list = list(map(num2str, index1, index2, index3))
    label_list = list(map(num2str, label1, label2, label3))

    return (prediction_list, label_list)

In [44]:
def find_diff(list1, list2):   
    if "".join(list1) != "".join(list2):
        return("".join(list1), "".join(list2))
    else:
        return(True)

In [45]:
x_test, y_test, y_test_small = data_genelization(sample_size = 3)
prediction_list, label_list = predict_results_only_3(model, x_test, y_test)
#prediction_list, label_list = predict_results_only_3(model, x_train, y_train)

1000/1000 [==============================] - 0s 81us/step

acc: 100.00%


In [54]:
print("Top 6 predictions:")
for i in range(6):
    print("".join(prediction_list[i]), "".join(label_list[i]))

Top 6 predictions:
WTG WTG
WHL WHL
QUE QUE
PHU PHU
IJY IJY
XTE XTE


In [60]:
diff = list(map(find_diff, prediction_list, label_list))
output = []
for x in diff:
    if x not in output:
        output.append(x)
print("Show some errors:")
output.remove(True)
for i in range(6):
    print(output[i])
print("The num of total errors:", len(output))
print("The accuracy:", 1-len(output)/1000)

Show some errors:
('MQD', 'MQA')
('KSO', 'KSA')
('NSO', 'NSA')
('DGC', 'DGA')
('ZMC', 'ZMA')
('TUO', 'TUA')
The num of total errors: 36
The accuracy: 0.964


## For 4 letters

In [64]:
x_train, y_train, y_train_small = data_genelization(sample_size=4)

In [65]:
model = Sequential()
model.add(Dense(20, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(y_train.shape[1], activation='sigmoid'))
# change loss from possion to binary it works well :P
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [66]:
model.fit(x_train,y_train,epochs = 300)

Epoch 1/300
1000/1000 [==============================] - 0s 486us/step - loss: 0.6649 - acc: 0.7153
Epoch 2/300
1000/1000 [==============================] - 0s 30us/step - loss: 0.5365 - acc: 0.9304
Epoch 3/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.2811 - acc: 0.9611
Epoch 4/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.1722 - acc: 0.9615
Epoch 5/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.1655 - acc: 0.9615
Epoch 6/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.1636 - acc: 0.9615
Epoch 7/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.1626 - acc: 0.9615
Epoch 8/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.1618 - acc: 0.9615
Epoch 9/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.1612 - acc: 0.9615
Epoch 10/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.1607 - acc: 0.9615
Epoch 11

1000/1000 [==============================] - 0s 32us/step - loss: 0.0618 - acc: 0.9792
Epoch 84/300
1000/1000 [==============================] - 0s 33us/step - loss: 0.0611 - acc: 0.9794
Epoch 85/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0603 - acc: 0.9796
Epoch 86/300
1000/1000 [==============================] - 0s 30us/step - loss: 0.0597 - acc: 0.9800
Epoch 87/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.0589 - acc: 0.9802
Epoch 88/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0582 - acc: 0.9805
Epoch 89/300
1000/1000 [==============================] - 0s 32us/step - loss: 0.0576 - acc: 0.9805
Epoch 90/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0570 - acc: 0.9809
Epoch 91/300
1000/1000 [==============================] - 0s 30us/step - loss: 0.0563 - acc: 0.9812
Epoch 92/300
1000/1000 [==============================] - 0s 30us/step - loss: 0.0557 - acc: 0.9814
Epoch 93/300


1000/1000 [==============================] - 0s 33us/step - loss: 0.0280 - acc: 0.9913
Epoch 165/300
1000/1000 [==============================] - 0s 33us/step - loss: 0.0278 - acc: 0.9914
Epoch 166/300
1000/1000 [==============================] - 0s 33us/step - loss: 0.0275 - acc: 0.9915
Epoch 167/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0274 - acc: 0.9913
Epoch 168/300
1000/1000 [==============================] - 0s 31us/step - loss: 0.0272 - acc: 0.9916
Epoch 169/300
1000/1000 [==============================] - 0s 30us/step - loss: 0.0270 - acc: 0.9917
Epoch 170/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.0267 - acc: 0.9918
Epoch 171/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0265 - acc: 0.9920
Epoch 172/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0262 - acc: 0.9919
Epoch 173/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0261 - acc: 0.9922
Epoc

1000/1000 [==============================] - 0s 33us/step - loss: 0.0152 - acc: 0.9962
Epoch 246/300
1000/1000 [==============================] - 0s 34us/step - loss: 0.0151 - acc: 0.9962
Epoch 247/300
1000/1000 [==============================] - 0s 36us/step - loss: 0.0150 - acc: 0.9961
Epoch 248/300
1000/1000 [==============================] - 0s 34us/step - loss: 0.0148 - acc: 0.9963
Epoch 249/300
1000/1000 [==============================] - 0s 29us/step - loss: 0.0147 - acc: 0.9964
Epoch 250/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0147 - acc: 0.9963
Epoch 251/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0146 - acc: 0.9964
Epoch 252/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0144 - acc: 0.9967
Epoch 253/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0144 - acc: 0.9964
Epoch 254/300
1000/1000 [==============================] - 0s 28us/step - loss: 0.0143 - acc: 0.9965
Epoc

However, we should not trust the accuracy results

## Deep learning the deep learning model

In [22]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from myfun import caeserde
from myfun import data_genelization
from myfun import data_test
key = 3
size = 26

Let strat with the simpliest model, say our alphabet has there letter ABC and the "caeser" function is to shift one place, ie. shift ABC to BCA.

In [28]:
x_train, y_train, y_train_small = data_genelization(sample_size = 2,loops = 1000, size = 3, key = 1, x_as_vector = False, y_as_vector = False)

In [29]:
# now we are going to train it in our model
model = Sequential()
model.add(Dense(5, input_dim=x_train.shape[1], activation='relu', name = "input"))
model.add(Dense(y_train.shape[1], activation='sigmoid', name = "layer1"))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
model.fit(x_train,y_train,epochs = 150)

Epoch 1/150
1000/1000 [==============================] - 0s 404us/step - loss: 0.6844 - acc: 0.5315
Epoch 2/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6607 - acc: 0.6298
Epoch 3/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6399 - acc: 0.6413
Epoch 4/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.6211 - acc: 0.6878
Epoch 5/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.6035 - acc: 0.7145
Epoch 6/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.5869 - acc: 0.7213
Epoch 7/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.5693 - acc: 0.7372
Epoch 8/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.5501 - acc: 0.7745
Epoch 9/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.5325 - acc: 0.7772
Epoch 10/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.5151 - acc: 0.7772
Epoch 11

1000/1000 [==============================] - 0s 23us/step - loss: 0.0358 - acc: 1.0000
Epoch 84/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0352 - acc: 1.0000
Epoch 85/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0345 - acc: 1.0000
Epoch 86/150
1000/1000 [==============================] - 0s 24us/step - loss: 0.0339 - acc: 1.0000
Epoch 87/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0333 - acc: 1.0000
Epoch 88/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0327 - acc: 1.0000
Epoch 89/150
1000/1000 [==============================] - 0s 25us/step - loss: 0.0321 - acc: 1.0000
Epoch 90/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0316 - acc: 1.0000
Epoch 91/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0311 - acc: 1.0000
Epoch 92/150
1000/1000 [==============================] - 0s 23us/step - loss: 0.0305 - acc: 1.0000
Epoch 93/150


Let's see what did the model learn!

In [31]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (Dense)                (None, 5)                 35        
_________________________________________________________________
layer1 (Dense)               (None, 6)                 36        
Total params: 71
Trainable params: 71
Non-trainable params: 0
_________________________________________________________________


It shows that we have 71 parameters. In the first layer, we have 30 weights and 5 biases. In the second layer, we have 30 weights and 6 biases which show as follow:

In [32]:
model.get_weights()

[array([[ 0.5230295 , -2.3722856 , -0.91483843,  0.9904725 , -2.0497599 ],
        [ 0.5239528 , -2.0380375 ,  2.315268  ,  0.71013767,  2.8065956 ],
        [ 0.49922538,  1.9143298 , -0.91098964,  0.9905842 ,  0.5758578 ],
        [-1.188174  ,  1.0506359 , -0.2596239 , -2.4396398 ,  0.8528697 ],
        [-1.1856221 ,  0.7440861 , -0.53387815,  1.9751233 ,  2.1526575 ],
        [ 2.0391617 ,  1.6623969 ,  2.4390411 ,  0.5798911 , -0.12870102]],
       dtype=float32),
 array([0.6622595, 1.3193262, 1.170595 , 1.4491769, 1.1961169],
       dtype=float32),
 array([[-0.1914282 ,  0.06342135,  0.9865053 , -1.7767843 ,  2.4452999 ,
         -0.830269  ],
        [-2.1160614 ,  2.7547426 , -2.2330601 , -1.1951566 ,  0.20668276,
          0.33688462],
        [ 1.3490559 , -1.2889181 , -1.0776172 , -1.7162324 ,  1.3834927 ,
         -0.3855466 ],
        [-1.6822165 , -0.6808207 ,  1.5137229 ,  2.424756  , -0.26901057,
         -2.9711552 ],
        [ 1.9215815 , -0.06922591, -2.0719502 ,  0.

In [20]:
weights = model.layers[0].get_weights()[0]
biases = model.layers[0].get_weights()[1]

In [34]:
from keras.models import Model
# Set one layer as output we can get every layers' information given the input

dense1_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('input').output)

dense1_output = dense1_layer_model.predict(x_train)

In [46]:
x_train[1]

array([0, 0, 1, 1, 0, 0])

In [45]:
y_train[1]

array([0, 1, 0, 0, 0, 1])

In [41]:
dense1_output[1]

array([0.0000000e+00, 4.2842922e+00, 0.0000000e+00, 1.2123585e-04,
       2.6248446e+00], dtype=float32)

In [36]:
dense2_layer_model = Model(inputs=model.input, outputs=model.get_layer('layer1').output)

dense2_output = dense2_layer_model.predict(x_train)

In [37]:
dense2_output[1]

array([1.8543303e-03, 9.9991524e-01, 3.9637089e-06, 2.2812188e-03,
       2.1130741e-03, 9.9756479e-01], dtype=float32)

As we can see, after calculating by two layers weights, the training data reduce the 1 value in the origin place and increase the value corresponding to the label place with value 1.

## Bad activation function and loss

Let's see if we choose a bad activation function what would happened.

In [52]:
# now we are going to train it in our model
model = Sequential()
model.add(Dense(5, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(y_train.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [54]:
model.fit(x_train, y_train, epochs = 100)

Epoch 1/100
1000/1000 [==============================] - 0s 33us/step - loss: 1.3923 - acc: 0.5190
Epoch 2/100
1000/1000 [==============================] - 0s 34us/step - loss: 1.3921 - acc: 0.5730
Epoch 3/100
1000/1000 [==============================] - 0s 28us/step - loss: 1.3920 - acc: 0.5770
Epoch 4/100
1000/1000 [==============================] - 0s 26us/step - loss: 1.3918 - acc: 0.6490
Epoch 5/100
1000/1000 [==============================] - 0s 27us/step - loss: 1.3917 - acc: 0.5380
Epoch 6/100
1000/1000 [==============================] - 0s 28us/step - loss: 1.3915 - acc: 0.5770
Epoch 7/100
1000/1000 [==============================] - 0s 25us/step - loss: 1.3914 - acc: 0.5210
Epoch 8/100
1000/1000 [==============================] - 0s 27us/step - loss: 1.3912 - acc: 0.5180
Epoch 9/100
1000/1000 [==============================] - 0s 25us/step - loss: 1.3911 - acc: 0.5170
Epoch 10/100
1000/1000 [==============================] - 0s 23us/step - loss: 1.3910 - acc: 0.5410
Epoch 11/

1000/1000 [==============================] - 0s 22us/step - loss: 1.3872 - acc: 0.5130
Epoch 84/100
1000/1000 [==============================] - 0s 23us/step - loss: 1.3871 - acc: 0.5250
Epoch 85/100
1000/1000 [==============================] - 0s 22us/step - loss: 1.3871 - acc: 0.5140
Epoch 86/100
1000/1000 [==============================] - 0s 22us/step - loss: 1.3871 - acc: 0.5170
Epoch 87/100
1000/1000 [==============================] - 0s 22us/step - loss: 1.3871 - acc: 0.4790
Epoch 88/100
1000/1000 [==============================] - 0s 22us/step - loss: 1.3871 - acc: 0.4990
Epoch 89/100
1000/1000 [==============================] - 0s 23us/step - loss: 1.3871 - acc: 0.4380
Epoch 90/100
1000/1000 [==============================] - 0s 25us/step - loss: 1.3870 - acc: 0.5080
Epoch 91/100
1000/1000 [==============================] - 0s 25us/step - loss: 1.3870 - acc: 0.4770
Epoch 92/100
1000/1000 [==============================] - 0s 27us/step - loss: 1.3870 - acc: 0.4990
Epoch 93/100


As we can see, the accuracy cannot converge to 1 because the softmax and categorical cross entropy treat the output as a distribution, however, it is not a classfication problem. This time our output has two value should be 1, so it is not suitable to use softmax and categorical crossentropy.

In [55]:
model.predict(x_train)[1]

array([3.17837621e-05, 4.99764025e-01, 5.15444517e-05, 1.03189086e-04,
       1.24050755e-04, 4.99925375e-01], dtype=float32)

In [58]:
sum(model.predict(x_train)[1])

0.999999968251359